### ISSUE TITLE
Channel name length restriction is too short

### ISSUE THREAD

**Issue by TelepathicGrunt** [PaperSpigot/Paper#10003]
### Expected behavior

Channel names can be allowed to be longer than 64 characters. Plugins channels are for interop with client mods, if modded frameworks such as NeoForge or Fabric don't enforce a limit, Paper shouldn't either. 

### Observed/Actual behavior

I got this bug report about my mod unable to connect to a Paper server on a Velocity server. I was told to report this as this network channel name limit is quite odd and very short.
https://github.com/TelepathicGrunt/Bumblezone/issues/315

Log from the user: https://pastebin.com/xyM0sFfB

> org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 75 - 'the_bumblezone:networking/the_bumblezone/queen_randomize_trades_sync_packet.
>         at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:500) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

### Steps/models to reproduce

Use 1.20.1 Bumblezone to connect to a Velocity server running Paper.

### Plugin and Datapack List

N/A

### Paper version

N/A (user did not say but I'll bring them to this issue report)

**Comment by Darmoed228** [comment]
Hello. My problem was solved in a simple way. I wanted to have several servers on the same IP, united in one network. Go to the hub and from there already choose through the NPC on which server to go. One of them was a server with fabric modpack. Velocity kicked when trying to connect to the hub with modpack client and with this error.  Because the hub server was on paper. I set up a redirection that the players who have the modpack client go straight to the fabric server. The rest of the players are directed to the hub to select paper servers. I caused this issue to appear here, so I guess I can close it. Sorry for the inconvenience, good luck!
