### ISSUE TITLE
Farmland not being fertilised 

### ISSUE THREAD

**Issue by papasot08** [PaperSpigot/Paper#10075]
### Expected behavior

Some farmland blocks aren’t getting fertilised even if they are directly touching water 

### Observed/Actual behavior

On my server, there is an area of farmland that doesnt get fertilised when water is nearby. Its a 5x6 wheat farm on the ocean, so the bottom of the  block is always touching water. Im reporting that because i had this problem for 3 years and didnt think anything of it and I never had the problem on the vanilla server software

### Steps/models to reproduce

This happens randomly, but it’s more common when there are bigger blocks near the farmland (farmland is smaller than other blocks like cobblestone) and only when there is water under the farmland 

### Plugin and Datapack List

no plugins / datapacks are used 

### Paper version

version 1.20.2, build 318

**Comment by Nacioszeczek** [comment]
Both Paper and vanilla don't water the block if the block is not at the same level as the water.
It would be great if you could provide us with the world that this happens on; unless I misunderstood what you mean by "the bottom of the block is always touching water"?

![image](https://github.com/PaperMC/Paper/assets/41339226/0a7a8d2d-8607-469b-98cd-ae6d99c9ee5b)

**Comment by ioannis2008** [comment]
I’m from bedrock edition now, but the problem is still the same. The farmland is at the same level as the water and nearby farmland is getting fertilised.
(I installed geyser mc to play on bedrock)
[image0.png][image1.jpeg][image2.png]

On 25 Dec 2023, at 1:22 AM, Oliwier Miodun ***@***.***> wrote:

﻿

Both Paper and vanilla don't water the block if the block is not at the same level as the water.
It would be great if you could provide us with the world that this happens on; unless I misunderstood what you mean by "the bottom of the block is always touching water"?

image.png (view on web)<https://github.com/PaperMC/Paper/assets/41339226/0a7a8d2d-8607-469b-98cd-ae6d99c9ee5b>

**Comment by Nacioszeczek** [comment]
We don't provide support for Bedrock Edition and Bedrock's behavior is not something we work to achieve.

If you have an inconsistency between Java Edition and Paper please send your images again through GitHub as replying to the e-mail didn't seem to attach those.
