### ISSUE TITLE
Fireball setVelocity incorrectly sets power

### ISSUE THREAD

**Issue by kennytv** [PaperSpigot/Paper#10186]
See https://github.com/PaperMC/Paper/pull/9815#discussion_r1461306045

The patch should probably be reverted and maybe a new setPower method added

**Comment by SuperKael** [comment]
Rather than reverting the patch, perhaps adding a call to super.setVelocity wouldsolve the issue? The problem is that setDeltaMovement is not being called. Fireballs seem to be continuously adjusting their delta movement based on a weird interplay of their power and their 'inertia,' which if I'm mental-mathing right should result in them gradually decelerating. Anyways, right now, both setDirection and setVelocity are only changing the power, and not the delta movement, which means that the new power values are being added to the previous delta movement, creating an effect akin to acceleration. When the new direction/velocity is applied, the delta movement needs to be changed as well to ensure that the fireball will actually be moving in the new direction.
