### ISSUE TITLE
C++ within Java? (extern C shenanigans)

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [PaperSpigot/Paper#10192]
### Is your feature request related to a problem?

Negative. I'm just posting it here because I couldn't find the right place for it.

### Describe the solution you'd like.

Not sure if this is the right channel for it, but...

Today I learned about this:

_"C++ got this nice `extern C` thingy that makes the compiler use C-style linkage for parts of your code._
_and java has ways of calling c-style native libraries._

_that's how it interacts with your operating system and other stuff"_

So it's possible to use [compiled] C++ in a Java program, by calling the C++ code from within Java.

However... It does not work the other way. To my knowledge there's no way to directly call a Java function from within C++.

But maybe if you're *very* careful with where you use the code (and also inform users that it will need to be compiled for their platform), then this might be usable for a high-performance option in Paper.

Maybe.

I think I'll let the devs decide if it's worth it or not.

### Describe alternatives you've considered.

Not applicable

**Comment by MiniDigger** [comment]
Hey, thanks for raising this!
The team is already aware of the multiple ways to call native code in java.
In general, modern java is approaching native performance, so the benefits aren't as big as they once were, so the overhead and complexity isn't worth it.
It makes much more sense to improve or replace existing java code with better java code, like the team has been doing for a decade now with great success.

Note that paper already utilizes native code for some things, in particular networking on Linux is using native epoll.

**Comment by electronicboy** [comment]
I just generally wanted to say,

A large part of the reason why the projects within this space can thrive and exist, like forge, fabric, etc; is because they rely on the Java code being decompilable and runnable in many places, the fact that we can modify mojang code (either at runtime or beforehand), effectively, is what allows these projects to add in their hook points and such to easily expose to mods, plugins, etc, to carry their goals on without impacting vanilla code too much, as, for the most part, it is vanilla code. 

There have been many projects that tried to rewrite the entire server into a different language, all of which generally hit the stumbling blocks of there being 15-years worth of features and such that they'd need to reimplement to even come close to vanilla parity. in order to justify native code for various things, you'd need to justify rewriting enough of a mechanism in order to counteract the overheads, which in turn brings you back to this issue which has plagued rewrites of the server software for years.

Calling native code from Java has been a thing for many decades, but calling native code from Java has many side effects, it has some headaches with the garbage collector, and anything you pass into native code effectively needs to be copied in and back out. This is why it generally only makes sense to use native code in places where there is a decent amount of memory able to be passed in and processed in one glob, or cases, where the OS or native libraries have mechanisms that are more performant than Java built-ins for various operations, i.e. native compression, can pass decently sized buffers over to a compressor which is more performant than what java offers (this, however, is less of a win with modern java, but, it's already there), and networking is much better when the OS can wake up your network pipeline in a more efficient manner than having to ask them "do you have any data for me?" outside of that, most operations are just far too small to have any performance gains worth the efforts of rewriting code and dealing with compiling native code for the 20 dozen platforms people expect us to support. We didn't go out of our way to implement features such as paperclip to then tell people that they'll need to install a full compiler chain on the OS in order to run the software.
