### ISSUE TITLE
Minecarts teleport visually under the blocks

### ISSUE THREAD

**Issue by Tuchan** [PaperSpigot/Paper#10269]
### Expected behavior

Minecarts should stay on the track, or it should be handled like vanilla does, to keep it consistent:

https://github.com/PaperMC/Paper/assets/43300571/628f2e33-449b-413a-bc33-f484c0804fa2

_This is a Singleplayer world_

### Observed/Actual behavior

Whenever minecarts have an additional block under their normal track, they visually teleport to that track instead of staying at the intended one. The entity is still there, just invisible until you update the rail block where it visually teleported to:

https://github.com/PaperMC/Paper/assets/43300571/ca504609-2d3f-4c43-b70e-a7f4e27d3073

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/43300571/ca504609-2d3f-4c43-b70e-a7f4e27d3073

### Plugin and Datapack List

Clean install:
![clean install](https://github.com/PaperMC/Paper/assets/43300571/0987bbc7-85af-4dd8-8dc5-3a5fc4c0f708)

### Paper version

[15:41:12 INFO]: This server is running Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87)

**Comment by Malfrador** [comment]
This is a client-side issue with minecart rendering that has existed since 1.14: [Mojira](https://bugs.mojang.com/browse/MC-158169)

There is nothing Paper can do to fix this, as on the server the Minecart is in the correct place. When you press F3+B you can also see that the hitbox stays in the correct place as well.
