### ISSUE TITLE
Adding 1.21 experimental content to the respective maps for 1.20.4

### ISSUE THREAD

**Issue by oliviathevampire** [PaperSpigot/Paper#10286]
### Is your feature request related to a problem?

In 1.20.4/5 Mojang have the 1.21 experimental features under a toggle, and if we enable that toggle, afaik plugins won’t really be able to work with them since they’re not in the code.

### Describe the solution you'd like.

Adding the new blocks and items to their respective classes

### Describe alternatives you've considered.

Idk if there is any alternatives

**Comment by Warriorrrr** [comment]
New 1.21 blocks, items and entities already have classes/fields, are there any that don't?

**Comment by oliviathevampire** [comment]
Nope, but by default none can be used other than when using the experiment. Not sure how Paper handles this

**Comment by electronicboy** [comment]
Things like the Material classes, etc, should already exist; if there are missing elements, we'd prefer issues identifying these, rather than a "do stuff" feature request

**Comment by Leguan16** [comment]
I mean, Spigot and Paper don't add mid-snapshot-phase features. The features you see in the API are there because of minor .2,.3,.4 releases. It is never planned to add snapshot stuff into the game. Until it's been released with a major/minor version. At least not at the moment. So I hope this further answers your question.
