### ISSUE TITLE
Make whitelist enabled by default

### ISSUE THREAD

**Issue by MrGeoTech** [PaperSpigot/Paper#10309]
### Is your feature request related to a problem?

Recently, more and more people have become aware of server scanning and using it to find servers. As a result, it has become shockingly easy to find server that are open and ripe for griefing. One of the easiest ways to prevent this is by enabling a whitelist. For a lot of new server owners, a whitelist only really comes to light after they have already been griefed. I feel that if the whitelist was enabled by default and maybe even a warning message when the server whitelist is turned off (and when the server is started and the whitelist is disabled), new server owners will recognize the importance of this issue. Up until now, simply not sharing your ip has been enough but we are at a point in time where more is needed and I think something as simple will drastically help with the issue at hand.

### Describe the solution you'd like.

Enable whitelist by default, warn the command sender about the dangers of disabling the whitelist when disabled, and a warning when starting the server with the whitelist disabled.

### Describe alternatives you've considered.

There could be and argument that just documenting enabling a whitelist in the setup docs would be enough but I feel that is not enough, even if it is documented as something required to do when first setting up a server.

### Other

I realize that this should be a Mojang issue but as they are not doing anything about it themselves, I feel as the most popular Minecraft server software, Paper has the responsibility to keep its users safe from dangers they might not even be aware of. To me, it seems like a simple thing to do that will have a large impact on the security of Paper's users while also not being too much of a hassle for server owners who don't want the whitelist enabled. I'm also hoping that this will set a precedent that other server software and potentially even Mojang will recognize.

**Comment by TetraTheta** [comment]
I think this kind of request should go to Mojang directly, rather than PaperMC.

Mojang's decision is setting `white-list`(enable whitelist) and `enforce-whitelist`(kick players not on whitelist) to `false`. I don't think PaperMC should interfere with it.

If Paper enforces whitelist by default, that said 'new server owners' won't be able to figure out how to allow people to get in their server.

If a server is griefed, server owner is also responsible for the incident. Server owner must know how their server is configured, by carefully reading the documentation. PaperMC already offers [detailed documentation](https://docs.papermc.io/paper/reference/configuration). That's enough for PaperMC. Anything further should be in server owner's responsibility.

**Comment by Leguan16** [comment]
In the other hand, this would probably cause people flood the help chats to ask why they cannot join their fresh server.

**Comment by lynxplay** [comment]
I want to close this feature request as not planned, however I'll leave this open for other people to chime in on.

The whitelist is obviously a powerful tool to protect servers from griefing (given that the server runs in a proper online-mode setup). Port scanning isn't complex to implement.
Switching the default here however feels rather painful for a couple of reasons (some already listed above).

1. A whitelist enabled by default makes sense for one user group of paper, small server owners that host such servers for friends. E.g. the server owners that would actually want a whitelist. This however is obviously not the entire range of server owners. Administrators hosting public servers would now need to actively *disable* the whitelist again to get to their desired state. Its a tradeoff, not a one sided gain. As such, I agree with the prior comments, this probably lends better to mojangs ears than ours.

2. Changing such a crucial part of the servers default configuration also means we'd be potentially breaking tooling out there that relies on a basic server to be ready for public usage once the EULA has been agreed to. Automatic server provisioning software would now need to adapt to a paper-specific change and begin changing whitelist state of servers when creating them (as one example).

3. I also agree with the concern regarding people not being able to join their own server setup. While this to some degree then raises awareness of the whitelist feature, it would also flood help channels or server hosts (if your argument really stands that so many server owners are oblivious to the feature in the first place). I doubt many server hosts would actually follow suit with our decision in this regard, a customer that immediately runs into a whitelist wall after renting a server seems like an undesired outcome for most.

In the end I think underestimating server owners is not a road we want to go down. An enabled whitelist, regular backups, regular server software updates, proper server configuration: All things a server administrator has to know or learn when hosting their server on the internet.
We might be able to create some form of "next steps" section in our docs, pointing towards "best practices" for new server owners, but the false sense of security that paper is going to protect you from issues that really should be a server owners domain feels problematic.

**Comment by electronicboy** [comment]
I'm inclined to agree with lynx, changing this stuff so far down the line would impede many automated setups, and so rolling out something like this would be a pretty big change for many servers in terms of how they operate, that it would need a hefty lead in time to accommodate in order to make sure that we don't break peoples setups.

A best practices document page would allow us to inform people of this sort of stuff in a wider sense of the issue here, it's not our role as an organisation to take on the risks associated with exposing stuff to the public network, it's 100% on server owners to consider *what* they're doing here, as the majority of server owners are just going to disable the whitelist as soon as they want their friends to join, and in turn, you've solved nothing bar pretending that you've passed over the batten of responsibility.
