### ISSUE TITLE
Bell shaking methods don't return the correct values

### ISSUE THREAD

**Issue by JakeGBLP** [PaperSpigot/Paper#10305]
### Expected behavior

Bell#isShaking() should return true when the bell is shaking
Bell#getShakingTicks() should return an integer bigger than 0 right after a bell is rung

### Observed/Actual behavior

Bell#isShaking() always returns false
Bell#getShakingTicks() always returns 0

### Steps/models to reproduce

I don't have proper steps to show this, because I've been testing via Skript and an addon for Skript I have created (written in Java using this API) and additionally with Skript-reflect which reflects classes and methods, behavior is the same

### Plugin and Datapack List

```
[14:45:48 INFO]: Server Plugins (3):
[14:45:48 INFO]: Bukkit Plugins:
[14:45:48 INFO]:  - Lusk, Skript, skript-reflect
```

### Paper version

```> version
[14:46:10 INFO]: This server is running Paper version git-Paper-447 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 0052e2d)
You are running the latest version
Previous version: git-Paper-446 (MC: 1.20.4)
```

**Comment by lynxplay** [comment]
Cannot replicate, shaking and shaking ticks work fine.

We will need replication steps in java for this from you, otherwise I'll close this.

Be aware, that getBlockState() creates a snapshot unless you pass `false`.
If you take said snapshot at a point where it is not shaking but then you query the shaking boolean while it is shaking, it will return the old value at the point of snapshotting.
