### ISSUE TITLE
Information about plugin updates within the loading phase of plugins

### ISSUE THREAD

**Issue by CubBossa** [PaperSpigot/Paper#10316]
### Is your feature request related to a problem?

There is currently no way of knowing if a plugin is being run on a different version than before. Plugins create various configs and other files that may be version dependant and each plugin has to somehow track the version of these files within again another file or a "DO NOT TOUCH THIS" config field. This is not a problem perse but i think it could be improved

### Describe the solution you'd like.

Either a different lifecycle hook, like `onEnable` a `onPluginUpdate(String priorVersion)` with an attribute for the prior version. Or a method in the Plugin interface to get the prior version `@Nullable Plugin#getPriorVersion()`. This value would also tell me if the plugin is being run for the first time or not. This is too a scenario that I had to find workarounds for in my plugins.

A solution could be a simple `plugin-versions.json` that stores plugins and their version and refreshes the file after the startup of the server. Of course the danger would be that unexperienced administrators mess with the file in hope to update a plugin.

On the other hand, that json would be a nice tool for discord support, like "could you send me your plugin versions please" to look for incompatibilities.

### Describe alternatives you've considered.

The alternatives are around already, but not really clean code and you have to invent the wheel all over again for each plugin you make

**Comment by electronicboy** [comment]
This imho makes no sense, and most issues relating to this are already long solved using 3rd party tools which don't require you to reinvent the wheel, or are generally simple "does this file exist" type checks.

detecting if you're a fresh install is generally flawed, but moreso generally done for a "do I need to run the logic to create X" sort of deal, which is generally better handled with tooling already designed for handling migration/generation of stuff, configurate, flyway, etc.

I don't see what this adds, other than making it possible to move your version check logic into some method we call, but, you will still be generally handling schema versions instead of trying to make the human readable string mean something to the computer, and this wouldn't solve something that can't be handled in much better ways using existing tooling within the wider java ecosystem

**Comment by CubBossa** [comment]
As I said in the post itself I know that there are different ways to solve updating plugin files.
Still, I think it would improve the workflow and I don't see why "You can find other third party solutions" is an argument against providing information to the plugin that it should have anyways. 
I rather feel like it's a little step towards standardization in plugin development.

**Comment by electronicboy** [comment]
I don't see how it improves the workflow in any form or meaningful manner, you still need to validate the data versions before you can do any transformations, and you don't know if a server owner has deleted the folder for your plugin or not and now you need to recreate your on-disk data, etc. I do not see how this would improve anything, relying purely on a version string would also generally be a massive flaw in terms of how this would be handled, see, many plugins which have dev builds in which they might or might not include a build number.

**Comment by CubBossa** [comment]
Okay lets say you have a sqlite file that had been created with v1 of your plugin. You modified your plugin code and need to readjust the schemas in your sqlite file for v2. With the suggested interface I would run a set of statements on my database. But therefore I have to figure out if the existing file is of the old or new format. I could check the schemas or maybe have put a key value of the plugin version in the file or I have to create an aditional file, which all would be an extra step I have to do. Or I assume the version based on the API parameter, try to convert the sql and in case of an exception rollback and state the issue in console and disable the plugin.

I can of course do this check each time my plugin enables but it is not necessary when the plugin hasn't updated at all. This is a different step than creating the actual file if the administrator deleted it, which needs to be checked on each start up.

In my opinion this is a more clean approach, but its just a suggestion and its not that I need it to be added, I just thought this was helpful.

**Comment by electronicboy** [comment]
1) a string would not accurately convey whether a jar has changed or not; We would need to resort to hashing the plugin jar to determine if it has changed or not, rather than a plugin just checking its schema version, which means now that a single plugin doing a trivial set of queries to get what migrations have been applied, or the schema version, we now have to hash every single jar file to determine if it is still the same jar file as before, thus meaning that we're now introducing a chunk CPU churn into the lifecycle to support this.

2) The plugin version is generally meaningless to the schema version, so you're still generally going to need to store the schema version unless you're planning to have a huge giant case of conditional logic to apply which changes over what plugin version, but, that would also make development much harder because now you'd have an extra file to contend with when respinning a jar and your data to test.

I feel that this would generally be better served by the docs showcasing good practices on how to deal with this, either as a more DIY solution or through using libraries like Flyway, as opposed to just trying to coax in hook points in which you still end up having to do pretty much everything you where already doing, only saving you a handful of lines of code at the cost of slowing down server startup performance.
