### ISSUE TITLE
Non-whitelisted player triggers some plugin processing

### ISSUE THREAD

**Issue by SlimeDog** [PaperSpigot/Paper#10321]
### Expected behavior

Block non-whitelisted connection attempts before they are processed by plugins.

### Observed/Actual behavior

Occasionally, someone finds my whitelisted non-public server and attempts to connect. Since they are not whitelisted, the connection fails, but the attempt causes several plugins to react, notably LuckPerms (pre-login processing) and Multiverse-Inventories (inventory entry).

### Steps/models to reproduce

- Attempted connection with a non-whitelisted player account
- Find `Authenticator` processing in server logs (good)
- Find processing in LuckPerms database (not good)
- Find processing in Multiverse-Inventories data (not good)

### Plugin and Datapack List

Many, but irrelevant to the report. Will be provided on request.

### Paper version

```
> version
[08:31:30 INFO]: This server is running Paper version git-Paper-450 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 62b220a)
You are running the latest version
```

### Other

As port-scanners have become accessible to script-kiddies, this issue has become more frequent.

Note that `online-mode: true` and `white-list: true` in server.properties.

**Comment by Machine-Maker** [comment]
I think it's expected that some events fire for all connections regardless of whitelist status, so that plugins can change that behavior. 

My initial reaction is that it is on plugins, if they are listening to events before a whitelist check, to not handle players that aren't whitelisted or move such logic to after a whitelist check.

**Comment by electronicboy** [comment]
This is not a bug, the player needs to be authenticated before we can check if they're whitelisted, otherwise, who knows if they are who they say they are. Any changes to this entire thing would introduce some potentially risky logic or require us to check if a player is whitelisted multiple times or be API breaks, both of which are not really a viable option, imho

**Comment by SlimeDog** [comment]
I have no issue with authentication firing; obviously that is necessary. I do not think login processing should continue if the (authenticated) player is not whitelisted. The point of the whitelist (from an innocent server owner's perspective) is that no further processing should occur if the player is not whitelisted.

**Comment by electronicboy** [comment]
- client connects
- mojang does authentication on the account
- the pre login (process) events fire
- the login process starts, the server checks if the player is able to login or not; if not, the login event is fired with the correct disallow status, otherwise it is allowed; plugins can touch this stuff to change the messages, i.e. apply at X to be whitelisted; appeal bans at, etc

There is very little in terms of what we can do here relating to plugins which isn't getting rid of the pre login events and moving the ban/whitelist checks in a manner which breaks plugins ability to interface with these mechanisms.

**Comment by SlimeDog** [comment]
Thanks for the details. Much appreciated.
