### ISSUE TITLE
Waterlogged.isWaterLogged doesn't make the water flow

### ISSUE THREAD

**Issue by JeroenoBoy** [PaperSpigot/Paper#10431]
### Expected behavior

I expect the water to start flowing when I change the block state

### Observed/Actual behavior

The water does not flow. But the block does show the waterlogged visual
![image](https://github.com/PaperMC/Paper/assets/26047623/959ac3f9-e47c-450d-b0c1-ac99b5a17163)

### Steps/models to reproduce

code:
```kt
val targetBlockData = targetBlock.blockData
if (targetBlockData is Waterlogged) {
    targetBlockData.isWaterlogged = !targetBlockData.isWaterlogged
    targetBlock.blockData = targetBlockData
    return
}
        
```

### Plugin and Datapack List

FAWE, Kotlin-stdlib, LuckPerms, PlaceholderAPI, PlugManX, spark, CustomPlugin

### Paper version

1.20.4 git-paper-485

**Comment by Machine-Maker** [comment]
Ok, this is actually due to a missing feature. There needs to be a method added to Block to tick the fluid. We have `Block#tick` and `Block#randomTick`, but not `Block#fluidTick` to tick the FluidState which will trigger the water to flow. That is exactly how vanilla does it, schedules a tick for the FluidState 3 ticks after the block was waterlogged.

**Comment by JeroenoBoy** [comment]
Thanks a lot!
