### ISSUE TITLE
API for controlling new mob behaviours

### ISSUE THREAD

**Issue by sowelipililimute** [PaperSpigot/Paper#10443]
### Is your feature request related to a problem?

Probably related to #10442.
Related to #6862.

As Minecraft moves into the future, more and more of the new mobs are mostly controlled via the new systems instead of the old ones that the current Bukkit Goals API abstracts over, and the inability to control them from the Paper API is more glaring.

### Describe the solution you'd like.

A new abstraction (or perhaps retrofitting the existing one) for controlling mob behaviours

### Describe alternatives you've considered.

Using NMS in order to prod at the underlying Minecraft stuff myself. Whilst doable, NMS usage makes cross-version support an individual plugin issue instead of a communal solution in Paper

### Other

I guess it would be nice to have some sort of indicator in the existing API docs for what they don't support currently, maybe a `UnsupportedOperationException` to make failures easier to catch instead of silently not working/only returning `false`

**Comment by pontaoski** [comment]
looking at the implementation of the brain system across versions, it seems stable enough that short of mojang nuking the system out of nowhere in a future update, there's not much risk in doing a mostly 1:1 exposure of the API?

the one (1) thing that concerns me is that the set of available tasks tends to fluctuate a decent amount, but mostly in the direction of adding tasks/splitting existing tasks into multiple flavours
tasks in general are a bit weird from an API perspective because they're just subclasses that you instantiate individiually, and they have varied parameter types that preclude some sort of `createTask(Tasks.WALK_TO_POSITION)` method a la `spawnEntity` 
i mean i guess you could have `Task1`, `Task2`, `Task3`, `Task4`, etc. etc. tuple classes to encapsulate task parameters?

**Comment by pontaoski** [comment]
one thing i'm not sure about is if an API should be `LivingEntity#getBrain` with all of the methods similar to the minecraft implementation, or exposing the sensor/task methods on the entity itself the same way spigot did with `LivingEntity#getMemory`/`LivingEntity#setMemory`
