### ISSUE TITLE
Wolf armor gets damaged when EntityDamageEvent is cancelled

### ISSUE THREAD

**Issue by TothAdam0012** [PaperSpigot/Paper#10978]
### Expected behavior

Cancelling EntityDamageEvent should prevent wolf armor from taking damage since there's no incoming damage to defend against.

### Observed/Actual behavior

Even though EntityDamageEvent is cancelled the wolf armor takes damage and eventually breaks.

### Steps/models to reproduce

Create an empty plugin an register the following event
```java
    @EventHandler
    public void onEntityDamage(EntityDamageEvent e) {
        if(e.getEntityType() == EntityType.WOLF) {
            e.setCancelled(true);
        }
    }
```
After summoning a wolf tame it and put armor on it. When the wolf gets hit by the player the armor takes damage.

### Plugin and Datapack List

Empty/test plugin

### Paper version

```
[22:56:28 INFO]: Checking version, please wait...
[22:56:30 INFO]: This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-27-76c2f16 (MC: 1.21)
```

**Comment by Doc94** [comment]
I check internally and looks like the event is called in actuallyHurts (in the final) what is only called if the wolf not has armor (or the damage ignore the wolf armor) currently in upstream is more easy fix that because the event now is created before the actuallyHurts is called and pass to the event later to actuallyHurst, but Paper has [EntityDamageItemEvent](https://jd.papermc.io/paper/1.21/io/papermc/paper/event/entity/EntityDamageItemEvent.html) what is called for damage in items like the Wolf Armor then you can use that for cancel the damage in Wolf Armor

**Comment by TothAdam0012** [comment]
Shouldn't EntityDamageItemEvent not even get called for this and just not damage the item? Or maybe not damage the item and call the event in a cancelled state.

**Comment by Goinging** [comment]
Pretty sure this is the issue you are talking about. https://hub.spigotmc.org/jira/browse/SPIGOT-7815

**Comment by Doc94** [comment]
> Pretty sure this is the issue you are talking about. https://hub.spigotmc.org/jira/browse/SPIGOT-7815

yeah in Upstream was already fixed, but here need handle EntityDamageItemEvent for that until https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/66e78a96b65b15c41e3c180beaa72c390b9d6153#nms-patches%2Fnet%2Fminecraft%2Fworld%2Fentity%2Fanimal%2FEntityWolf.patch is merged here

**Comment by CatBang** [comment]
Merge
https://github.com/PaperMC/Paper/pull/11102
