### ISSUE TITLE
Teleporting from any other dimension to the overworld fully heals you

### ISSUE THREAD

**Issue by TauCu** [PaperSpigot/Paper#10999]
### Expected behavior

Your health does not change.

### Observed/Actual behavior

Your health is set to full.

### Steps/models to reproduce

1. Go to hell :-)
2. take damage
3. minecraft:tp to someone or something in the overworld. Also works with essentials /tp, /back, /home and seemingly any other plugin teleport.

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/35522873/d8673051-7c96-4592-baa7-90c85b20bff5)

### Paper version

```
[16:28:56 INFO]: This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-15-2df432f (MC: 1.21)
```

### Other

clean server with new world, defaults on everything.

**Comment by Lulu13022002** [comment]
Can replicate, this is because spigot doesn't recreate the player instance for some cross-world tp and respawn, they already put a "fix" (bandaid) here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/f993563ee5a5cd2282762735d2e6a332321e82d4#nms-patches%2Fnet%2Fminecraft%2Fserver%2Flevel%2FEntityPlayer.patch?t=921
