### ISSUE TITLE
Paper 1.21.1 Build #15 Endermite No Spawn Issue

### ISSUE THREAD

**Issue by IgnjatRadojicic** [PaperSpigot/Paper#11264]
### Expected behavior

Endermites spawning when a player uses enderpearls although the chance is low statistically it's very impossible for one not to spawn in 200+ pearls.

### Observed/Actual behavior

No Endermites spawned in 200+ pearls has also been tested by a Paper Triage Team member. 

![Capture11111](https://github.com/user-attachments/assets/42a3623c-a4d8-401c-8a1d-c4cfa5d0011c)

### Steps/models to reproduce

Try to get a Endermite to spawn

### Plugin and Datapack List

Clean Paper Install no plugins no datapacks no settings touched.

### Paper version

Latest (Current) Build #15 of 1.21

**Comment by 456dev** [comment]
cannot reproduce: paper built from master i got an endermite in 10 pearls
![image](https://github.com/user-attachments/assets/a5f82c58-5d8b-4291-9e1a-9f777c28c200)

(also tested in the end, since i saw that on discord)

<details>
<summary>
Reproduction version
</summary>

![image](https://github.com/user-attachments/assets/3b86405c-f5a5-41a1-8487-3e292b3e53ad)

</details>

**Comment by MartiThaWizz** [comment]
Could it be then the build #15  or are we just this unlucky for not to get one spawn?

**Comment by lynxplay** [comment]
Can also not replicate. Make sure that the mobspawning gamerule is not set to false.
