### ISSUE TITLE
Villager AI Sync Chunk Load

### ISSUE THREAD

**Issue by PedroMPagani** [PaperSpigot/Paper#11415]
### Profile link

*

### Description of issue

![image](https://github.com/user-attachments/assets/156caeab-803d-4d41-b228-f5aabc2ee230)
The villager check for bed is sort of causing a chunk load, it'd be nice if there is a check for the chunk present/not so that this does not happen. This seems to be mostly affected when there's a huge number of chunk generations or so, cannot confirm with 100% sureness, but I am seeing this call on donut

### Plugin and Datapack List

.

### Server config files

.

### Paper version

.

### Other

.

**Comment by codebycam** [comment]
Hey @PedroMPagani, 
I'm closing this due to you not providing actual logs (a screenshot isn't helpful), and the report being incomplete which makes it more difficult for the people that spend their free time working on Paper. 

Please feel free to create another issue with actual logs, code examples to reach your issue, and a more complete report. 
Cheers!
