### ISSUE TITLE
Not resolved

### ISSUE THREAD

**Issue by Hundr** [PaperSpigot/Paper#11471]
> Paper has expanded the chat API in a manner that allows plugins to do fancier chat things and it's 100% on plugins on how they interact with that. having two plugins installed which handle that is asking for issues, essentials for example has a config option which is enabled by default last I knew which will put the players pre/suffix into the display name of the player, and so if you're using another chat plugin, you'd want to disable that.
> 
> For support, please use the discord. 

 _Originally posted by @electronicboy in [#11470](https://github.com/PaperMC/Paper/issues/11470#issuecomment-2395341498)_

**Comment by lynxplay** [comment]
I don't know what this issue aims to accomplish. 

Cat already explained to you that third party software (the plugins you run) are responsible for correctly inter-operating. Beyond that, I'd suggest opening issue with the respective plugins used to construct these prefixes. *If* this ends up actually being an issue in papers API implementation, the developers of the respective plugins know their code and potential caveats a lot better than we do and should be able to open a proper issue on our tracker with actual reproduction steps.

Our discord was suggested as long lasting discussions/support is generally something we do not want on our github issue tracker, as it is reserved for bugs, not the process of figuring out if the issue comes from us, incorrect configuration, faulty plugin interop or even third party bugs.

Again, I'd urge you to open these issues with the developers of the plugin that serve these prefixes.

For what it is worth, a *super simple* setup with EssentialsChat, LuckPerms and Vault and chat config of
```yaml
chat:
  format: '&7{PREFIX}&r {GROUP} {DISPLAYNAME}&r &7{SUFFIX}&r: {MESSAGE}'
```
worked for me (bar the fact that the prefix is doubled, there is as config option as cat mentioned).

**Comment by Hundr** [comment]
Its easier to just go back to spigot.
