### ISSUE TITLE
Problems with ships

### ISSUE THREAD

**Issue by servicomcr** [PaperSpigot/Paper#11640]
### Expected behavior

When a ship falls into lava it bugs like this, it is not destroyed by a cactus either

https://youtu.be/pkAEUhC9Gn8

### Observed/Actual behavior

When a ship falls into lava it bugs like this, it is not destroyed by a cactus either

### Steps/models to reproduce

When a ship falls into lava it bugs like this, it is not destroyed by a cactus either

https://youtu.be/pkAEUhC9Gn8

### Plugin and Datapack List

 /datapack list
datapack list
[08:32:23 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[08:32:23 INFO]: There are no more data packs available

### Paper version

This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-130-4d2672e (MC: 1.21.1)

**Comment by codebycam** [comment]
Hello @servicomcr, I was unable to reproduce this issue on Paper 1.21.1 Build 131 or the latest version (1.21.3 Build 45). In all cases, whether I was in a boat or a minecart, entering lava instantly broke the vehicle. I tried a similar setup as shown in your video too (falling into lava, driving into lava, etc). 

Given the contents of your video I'm going to assume it's most likely being caused by a plugin (which you failed to list), and the best advice I can give is to follow some basic troubleshooting steps on our docs, such as a [binary search](https://docs.papermc.io/paper/basic-troubleshooting#binary-search).
