### ISSUE TITLE
Team Assignment Error

### ISSUE THREAD

**Issue by Raneter** [PaperSpigot/Paper#11749]
### Expected behavior

Players are placed on a team and visually stay on that team at all times they are assigned to do so.

### Observed/Actual behavior

Some specific players are randomly removed from that team visually in tab and don't obey team modification rules, but they can still be teleported under such team.

### Steps/models to reproduce

This is where it gets weird. This is only reproduced when I remove a bunch of people from a team after an extended period of time. This would only occur for a select few accounts after I left them on a team for an extended period of time.

### Plugin and Datapack List

Plugins

- Citizens
- DecentHolograms
- Essentials
- ImageFrame
- Multiverse-Core
- ProtocolLib
- SkBee
- Skript
- TridentCollision1 (this does nothing)
- WorldEdit

Datapacks

- vanilla
- paper
- bukkit

### Paper version

This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-77-2cd8c46 (MC: 1.21)

### Other

Here is what I wrote on Reddit. I mainly just need help solving this issue as its causing a lot of problems.

I own a Minecraft server. There are a select few accounts with a weird error where their team assignment is corrupted. When they are put on a team, they stay on that team for ~5 minutes but are then removed from that team aesthetically (as in they lose the team color in their name tag and the tab list, ignore collision rules etc.). When these corrupted players are kicked from the server, everyone is then kicked with the error "Network Protocol Error".

Here are some logs sent when someone is kicked.

```
[2024-12-14 17:16:26.600] [error] [17:16:26] [Render thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket@fcfcb78
[2024-12-14 17:16:26.628] [error] java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'Team1'.
```

Please help in any way, thanks.

**Comment by mbax** [comment]
Paper 1.21 build 77 came out in mid-July, and was before we even removed the experimental label. Build 130, the last for 1.21, was weeks later. That makes you wildly outdated for 1.21. You shouldn't be on *any* of those, however, as 1.21.1 came out pretty fast to fix some critical bugs and exploits and had its last updates in *November* which is significantly later. But even *that* is outdated at this point. You should be on latest 1.21.3 or 1.21.4 by now. 

First, upgrade the server and all your plugins and see if the issue persists. Maybe it was resolved in an update! If it's not, however, you will want to follow our guide on [finding the culprit](https://docs.papermc.io/paper/basic-troubleshooting#finding-the-culprit), in particular doing a binary search. Once you have identified the issue, your solution will vary:

* If it's one plugin causing the issue, report it to them and remove the plugin for now.
* If it's a result of multiple plugins conflicting, investigate if there's a feature in one that you can disable so that they get along. Depending on the issue, possibly report that.

For further support, once you're on a supported version of the server, feel free to ask us for advice on the Discord server.
