### ISSUE TITLE
1.21.4-14 experimental build: village raids won't go over level 4

### ISSUE THREAD

**Issue by ping-mee** [PaperSpigot/Paper#11748]
### Expected behavior

When a raid in a village is triggered it should go over level 4 if the difficulty is on hard.

### Observed/Actual behavior

When a raid is triggered it only goes to level 4 and then it declares victory when all the raiders a defeated.

### Steps/models to reproduce

1. Player is in survival mode
2. Player drinks amnious 5 potion
3. Player waits 30 seconds
4. Player goes into a village
5. Raid starts
6. Complete the waves

### Plugin and Datapack List

No datapacks are used.
The following plugins are used:
Simple Voice Chat
CustomDiscs
ImageFrame
PermissionsEx (not used, just install incase it is needed)
TabTPS
StatusPlugin

### Paper version

1.21.4-14-master@b746d9d

**Comment by kennytv** [comment]
Does the same happen in Vanilla 1.21.4, or is it a Paper-specific bug?

**Comment by ping-mee** [comment]
It only happened on paper

**Comment by codebycam** [comment]
> It only happened on paper

Are you sure your difficulty is on hard? You can check this by using `/difficulty` in the overworld. I ask because I just tested this on 1.21.4 Build 15 and I had no issue, I received the raid as expected going off the [raid wave composition](https://minecraft.wiki/w/Raid#Java_Edition). 

This was a fresh world, I joined, used `/difficulty hard`, consumed an Ominous Bottle and started the raid.

**Comment by ping-mee** [comment]
Got fixed. Was a problem with the server hoster. Very weird but they fixed it
