### ISSUE TITLE
Nether portals do not connect vice-versa

### ISSUE THREAD

**Issue by n0rbyt3** [PaperSpigot/Paper#6757]
### Expected behavior

Going through a nether portal A in the overworld will create a nether portal B in the nether. Walking through B in the nether will teleport the player to portal A in the overworld.

### Observed/Actual behavior

Walking through B creates a new portal C in the overworld. Walking through A still teleports correct to B.

### Steps/models to reproduce

- create a nether portal A in the overworld (left bottom at [1493, 32, -302], right top at [1493, 36, -305])
- this will create a nether portal B in the nether (left bottom: [198, 34, -20], right top: [198, 38, -23])
- go through B again
- a new portal C is created in the overworld (left bottom: [1584, 69, -166], right top: [1584, 73, -169]

### Plugin and Datapack List

Plugins: Chunky, LuckPerms, TreeGravity, WorldEdit
Datapacks: none

### Paper version

This server is running Paper version git-Paper-325 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4a0d935)
You are running the latest version
Previous version: git-Paper-321 (MC: 1.17.1)

**Comment by n0rbyt3** [comment]
Thanks to this link (https://www.minecraftforum.net/forums/support/java-edition-support/3028674-1-16-nether-portals-not-linking) I found out, I need to re-align the portals manually. So I created a new portal in the nether [186, Y, -37] and they are now linked vice-versa.

Is this an expected vanilla behaviour?

**Comment by electronicboy** [comment]
Make sure that you've got vanilla scaling set to true in paper.yml, as well as the default portal search/create radiuses (just, delete them if you're not sure)

This generally just looks like the typical way portals work, there is no permanent linking between them, and due to the maths it's not too uncommon that portal B doesn't find portal A and creates a new one, as there is no real "link" between them, just some maths to go search for it and if it's not found in the radius it searches, it won't link

**Comment by n0rbyt3** [comment]
paper.yml:

```yaml
portal-search-radius: 128
portal-create-radius: 16
portal-search-vanilla-dimension-scaling: true
```

Thanks for your explanation that there is no real linking. Like I found out, I needed to align manually (for the math).
