### ISSUE TITLE
Exception during command execution locks console

### ISSUE THREAD

**Issue by NichtStudioCode** [PaperSpigot/Paper#6857]
### Expected behavior

My plugin directly accesses the command dispatcher to create commands using Mojang's brigadier API. In order to check for required permissions, `LiteralArgumentBuilder.requires` is used. The provided predicate accesses the player object from the `CommandSourceStack` to check for permissions. This obviously throws an Exception when the command is executed from within the console. I don't want the console to execute the command, so that's fine. Spigot's (or Mojang's) implementation does not really consider this an error and just prints `A player is required to run this command here`.

![](https://i.imgur.com/6AMKAu6.png)

### Observed/Actual behavior

When using paper however, the following is printed:
![](https://i.imgur.com/B2FajHL.png)
This does not only look ugly, but also freezes the console input. (You can't type in the console anymore.)

### Steps/models to reproduce

1. Install [Nova](https://www.spigotmc.org/resources/93648/)
2. Try to type `nova items` in the console

OR

Create a command using the Brigadier API and throw an Exception in the `LiteralArgumentBuilder.requires` predicate.

### Plugin and Datapack List

[Nova](https://www.spigotmc.org/resources/93648/)

### Paper version

This server is running Paper version git-Paper-358 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3f043f7)

### Other

You can look at my code here:
https://github.com/xenondevs/Nova/blob/main/src/main/kotlin/xyz/xenondevs/nova/command/CommandManager.kt
https://github.com/xenondevs/Nova/blob/main/src/main/kotlin/xyz/xenondevs/nova/command/Command.kt

**Comment by jpenilla** [comment]
1) This issue basically says "I am doing something unsupported and having issues with it", which means our response will basically be "glhf".
2) You are not meant to throw exceptions in the requirement predicate. You are meant to return a boolean. You are invoking a method called getPlayer**OrException**. This is completely the fault of your code and nothing to do with Paper. Looking through the Brigadier and Minecraft source you can clearly see calls to `canUse` and `getRequirement` do **NOT** wrap requirement checks in trys. The difference here between Paper and Spigot, is that Spigot doesn't support Brigadier highlighting and suggestions in console whatsoever, so obviously this issue won't come up there.

**Comment by jpenilla** [comment]
For further context, `getPlayerOrException` and other similar `CommandSyntaxException`-throwing methods are meant to be used in argument parsers and command executors (not requirement checks).

**Comment by NichtStudioCode** [comment]
> The difference here between Paper and Spigot, is that Spigot doesn't support Brigadier highlighting and suggestions in console whatsoever, so obviously this issue won't come up there.

Spigot's implementation still calls the requirement predicate, though? Why is it catched there but not on Paper?
It's not hard to work around that problem, but I'm confused why you're refusing to fix such a simple issue when it basically breaks the parity paper promises to have with Spigot plugins.

**Comment by jpenilla** [comment]
Because the call to `CommandDispatcher#execute`, in `Commands#performCommand` is wrapped in a try catch for `CommandSyntaxException`.

This is because parsers and executors are expected to throw `CommandSyntaxException`s, which are then explicitly handled by brigadier in the parsing/execution code. You can even see this specified in the Javadoc for `execute`: `@throws CommandSyntaxException if the command failed to parse or execute` - not if the predicate threw. You are essentially throwing a random exception in a part of the pipeline not expecting exceptions, therefore it just bubbles up to the caller, which in this case was expecting `CommandSyntaxExeption`s for another reason. If you were to throw a random exception type not being handled for other reasons, you would have gotten a different error message.

The reason the exception is not caught during console tab completion is that we are not calling `execute throws CommandSyntaxException` for console completion/highlighting, we are calling `parse` which does not `throws CommandSyntaxException`, or any exception for that matter. Because `parse` is not meant to throw, we don't wrap it in a try catch like we would have if we were calling `execute throws CommandSyntaxException`. So essentially by throwing like this you are breaking the contract of `parse`, without technically breaking the contract of `execute`, which calls `parse`.

Additionally to respond to your comment, registering to the internal command dispatcher is not supported behavior on either Spigot or Paper. And again, your code is wrong on Spigot and on Paper, Spigot just doesn't have code which would expose this issue. There is no issue for Paper to fix here. I don't understand why it's so difficult for you to just fix your code. A (still bad) solution would be to just wrap your call in a try catch yourself, and return false... Since you're using kotlin it would even be as simple as `val player = it.entity?.bukkitEntity as? Player ?: return false` to do something better.

**Comment by NichtStudioCode** [comment]
Yeah, sorry, I misunderstood Spigot catching the exception as an indication that throwing exceptions in the `requires` predicate is allowed. I didn't know that there was any documentation for Brigadier, the Minecraft repository doesn't seem to host the javadoc jar (or it's not downloading for some reason)

You're right, it's not hard to fix (that is what I meant with _"It's not hard to work around the problem"_, I think you misunderstood me there), but I thought that it should be fixed on Paper's side because I believed that throwing exceptions in this context was okay.

Thank you for taking the time to clarify this 👍
