### ISSUE TITLE
Cannot Drop Air Check

### ISSUE THREAD

**Issue by dgrawns** [PaperSpigot/Paper#6889]
### Expected behavior

Data pack uses minecraft:air to prevent literally dropping items.

### Observed/Actual behavior

"Cannot drop air" error appears instead due to CraftBukkit check.

### Steps/models to reproduce

Attempt to drop the item "minecraft:air" and the error will show up.

### Plugin and Datapack List

Datapack: Dojutsu.

### Paper version

version git-Paper-378 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc2ecbc)

### Other

An idea to fix could be a config for this such as aircheck=true/false which would enable/disable the craftbukkit check for if air is being dropped.

**Comment by electronicboy** [comment]
need the actual full error message

**Comment by dgrawns** [comment]
From what I can tell, there wasn't much of an error, 

execute store result score @s d.dna_rng run loot spawn ~ ~-100 ~ loot dojutsu:dna_rng

This triggered the loot table to drop the item which was 'air'. It would then trigger: "An unexpected error occurred trying to execute that command." If you hover over this error it showed "Cannot drop air".

**Comment by GrifterMage** [comment]
Minor addition here, but this also happens when dropping the contents of a shulker box as part of a loot table, such as with [Phi](https://github.com/MinecraftPhi/MinecraftPhi-modules)--if there's an empty slot somewhere in the shulker, the contents of previous slots will drop, but once it hits the empty slot and throws the error the remainder of the contents are skipped.

**Comment by Doc94** [comment]
Well this issue its only related to the loot command.. then maybe can be a good fix make the commando avoid the empty ItemStacks for avoid throw the error.. i dont see another place where this can cause another error because already upstream add logic in another places for this cases...

PR in Upstream: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/1024/overview

**Comment by Machine-Maker** [comment]
I think that whole check should be moved to one of the addEntity methods instead. If the goal is to prevent ItemEntities from being added to the server which emtpy stacks (even though their first tick it'd be removed), no reason the check should throw an exception. Clearly there are several places where mojang is doing empty itemstack entities.

**Comment by Doc94** [comment]
yeah not sure since when this validation exists in Upstream... but with the another things in the method for set ItemStack not find a better fix than ignore empty items in the command. or can think a better fix if the PR its rejected

**Comment by Machine-Maker** [comment]
I think I need a more complete description of the use case data packs have for dropping empty stacks, like how do they do it, why do they do it, the mechanics of it, etc. A *simple* data pack that demonstrates the functionality data packs use this for would be great. That would help determine what the best fix for this is.

**Comment by Doc94** [comment]
By the moment this was "patched" in Upstream (https://github.com/PaperMC/Paper/commit/1358d1e9146ca80d0ff84a644c7796d20b39765c) in base this happen with the loot command.. but yeah like a few comments this its not a total fix..
