### ISSUE TITLE
Server crash after running for a while

### ISSUE THREAD

**Issue by TenkyuChimata** [PaperSpigot/Paper#6906]
### Stack trace

```
https://paste.gg/p/anonymous/23e8c054a0be4cacb80d6b8453f9f25e
```

### Plugin and Datapack List

Plugins: CMILib, ProtocolLib, Residence, EssentialsX, mcMMO, Viaversion, SkinsRestorer

### Actions to reproduce (if known)

Random crash, about once a day.

### Paper version

> version
[22:28:46 INFO]: Checking version, please wait...
[22:28:53 INFO]: This server is running Paper version git-Paper-384 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 51b7b60)
You are running the latest version

### Other

Oracle JDK 17.0.1
With 20gb of ram.

**Comment by TenkyuChimata** [comment]
with git-Paper-386:
https://paste.gg/p/anonymous/89478ef08e5f4de8a70f72858041fb9d

**Comment by RealCamar** [comment]
Does this happen without plugins?
Sounds like an issue with a plugin

**Comment by Chew** [comment]
Whoops, forgot to comment first.

1) `[10:40:20] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-384 (MC: 1.17.1) ---`
2) Your server is failing to load chunks in time, due to lag or something, not much we can do without a timings report.

For this kind of support, we recommend [our Discord server](https://discord.gg/papermc) or the [forums](https://papermc.io/forums)
