### ISSUE TITLE
Wandering Trader Per Player

### ISSUE THREAD

**Issue by LucidAPs** [PaperSpigot/Paper#6907]
### Is your feature request related to a problem?

Please add an option to have the existing spawn settings for wandering traders to be per player instead of global. I have a server with 50+ players and we haven't seen a trader in months.

### Describe the solution you'd like.

Add an option for the spawn chance to be per player instead of global.

### Describe alternatives you've considered.

Well there is this plugin https://www.spigotmc.org/resources/spawnwandering.84453/ but it doesn't seem trustworthy at all.

**Comment by jpenilla** [comment]
Rewriting the wandering trader spawn algorithm would be a lot of work for little to no benefit. I understand the Minecraft wiki says something about "only one wandering trader can be spawned in the world at a time", however this is not actually implemented anywhere in the code. You should be able to effectively do what you want by increasing the spawn rates, if you're getting no spawns at all while adjusting those configs, I would guess you're probably using bad values.

**Comment by LucidAPs** [comment]
> 

I understand, then perhaps if you wouldn't mind, could you give me some pointers, to make sure there are a lot of traders?
These are the values I am using and yet no wanderers to be found. All other mobs are spawning no problem.
    wandering-trader:
      spawn-minute-length: 2400
      spawn-day-length: 6000
      spawn-chance-failure-increment: 100
      spawn-chance-min: 100
      spawn-chance-max: 100

**Comment by jpenilla** [comment]
Due to the way the spawning logic works it's usually better (although not required) that the `spawn-day-length` is cleanly divisible by the `spawn-minute-length`. With your current configuration you would wait 7200 ticks between each spawn attempt, changing `spawn-minute-length` from 2400 to 2000 would change that to 6000 ticks.

By maxing the spawn chance and having 6000 ticks per spawn, you're going to be making spawn attempts 4x more often than vanilla, and they will all pass the spawn chance, however the vanilla rates just happen to be *really slow*, so if you have 50 players logged in you will probably want a value even lower than 6000.

Another thing to keep in mind is each spawn attempt that passes the "spawn chance" also has an additional 9/10 chance to fail, which isn't currently configurable.
