### ISSUE TITLE
Seed leak on packet data laval

### ISSUE THREAD

**Issue by moontaker** [PaperSpigot/Paper#6909]
### Expected behavior

Players are not supposed to generate the seed while randomly teleporting

### Observed/Actual behavior

Random player teleport allowed a player on a modified client to generate the server seed in seconds

### Steps/models to reproduce

/tpr (into the wild)
rest of the steps were done on the player's client (no info what client was used)

### Plugin and Datapack List

19.11 19:24:45 [Server] INFO Plugins (47): AdvancedPortals, AdvancedRegionMarket, AFKPlus, AltDetector, AuctionHouse, BetterChair, Brewery, BuycraftX, ChatColor2, ChestShop, Citizens, CoreProtect, DiscordSRV, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, GoldenCrates, GriefPrevention, GSit, HeadDatabase, HexNicks, HolographicDisplays, LiteBans, LuckPerms, MarriageMaster, NexEngine, OnePlayerSleep, PlaceholderAPI, PremiumVanish, ProtocolLib, Randomtp, Rankup, ShulkerboxPreview, SilkSpawners, SimpleStaffChat*, spark, Spartan, TAB, Timber, UltimateTrash, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard

### Paper version

1.17.1 (build 386)

### Other

Player executed /shop , the command is bound to EconomyShop plugin

**Comment by kennytv** [comment]
Not exactly sure what your random teleport plugin has to do with this being a Paper bug, but I'd suggest you join our Discord to get more help on how to prevent seed cracking through configuration and plugin changes.

**Comment by moontaker** [comment]
The rtp was done directly from essentials. Thanks for the reply, I will be joining the discord for further support, cheers!

**Comment by electronicboy** [comment]
> Random player teleport allowed a player on a modified client to generate the server seed in seconds

Minecraft world gen is determinate, i.e. same seed = ~same results, then there's aspects like structure gen which makes it easier to pick out datapoints which are easier to test against. You can tweak the feature seeds in paper.yml to help mitigate this to a degree, but, that's best done on a fresh world, otherwise, but, if somebody cares enough they can still reverse it, people have found the seeds for some of the "famous" screenshots from in the title screen and other places over the past few years.

Only true fix here is to not use minecrafts world generator but use something custom
