### ISSUE TITLE
Consider making Eigencraft Redstone default?

### ISSUE THREAD

**Issue by GabrielSieben** [PaperSpigot/Paper#6975]
### Is your feature request related to a problem?

The Eigencraft Redstone engine is faster than the stock Redstone implementation, but is not default because it may cause edge incompatibilities with Redstone (though a quick questioning of devs on Discord didn't remember anything in particular). It is most likely that any incompatibilities are strictly for extremely large or technical Redstone builds, and that the vast majority of standard Redstone builds would be unaffected.

### Describe the solution you'd like.

I would like to give Eigencraft a second-look for compatibility, and if no issues are found, I don't see any reason why Eigencraft couldn't be made the default Redstone engine. In my mind, we already patch out dupe glitches but give a way out for anyone personally affected; similarly, the Eigencraft Redstone engine would just be a significant performance boost with an opt-out for anyone doing something really niche (like technical builds).

Basically, in `paper.yml`, change the default from:
`    use-faster-eigencraft-redstone: false`
to
`    use-faster-eigencraft-redstone: true`

### Describe alternatives you've considered.

I don't think this feature request has alternatives.

**Comment by GabrielSieben** [comment]
Relevant patch for the Eigencraft engine:

https://github.com/PaperMC/Paper/blob/master/patches/server/0498-Optimize-redstone-algorithm.patch

Also of note is the original patch header (which may or may not be still accurate):

> This patch implements theosib's redstone algorithms to completely overhaul the way redstone works.
> The new algorithms should be many times faster than current vanilla ones.
> From the original author's comments, it looks like it shouldn't interfere with any redstone save for very extreme edge-cases.

**Comment by GabrielSieben** [comment]
Another possibility would be porting Alternate Current: https://github.com/SpaceWalkerRS/alternate-current (came up on Discord but that would be a separate issue and bigger than this request.)

**Comment by YanikKendler** [comment]
i mean.. people can change the engine if they want to, but it may be better to just leave it as an option

**Comment by RoseFMoidel** [comment]
Definitely a hard no from me, this would make technical YouTube tutorials much harder to use and any redstone inventions you create would have a chance of only working on paper servers (And others with this engine) meaning broken redstone timings if you ever make your server vanilla again. Please leave it off by default.

**Comment by LaurenceBarnes** [comment]
I would love with a port of "Alternate Current" being in Paper as a very performant third option in addition to complete vanilla functionality and Eigencraft.

**Comment by Titaniumtown** [comment]
> I would love with a port of "Alternate Current" being in Paper as a very performant third option in addition to complete vanilla functionality and Eigencraft.

I have already ported alternate current myself (https://gitlab.com/Titaniumtown/JettPack/-/blob/main/patches/server/0023-port-alternate-current.patch). I'm gonna work on making it a config option later and possibly PRing it to Paper.

**Comment by GabrielSieben** [comment]
> Definitely a hard no from me, this would make technical YouTube tutorials much harder to use and any redstone inventions you create would have a chance of only working on paper servers (And others with this engine) meaning broken redstone timings if you ever make your server vanilla again. Please leave it off by default.

This is why I would advocate that we experiment with Eigencraft because nobody can exactly quantify an example, at this point, showing where (if at all) Eigencraft breaks things. We first need to find (in my view) a place where Eigencraft breaks, and then determine how many builders would be affected.

Paper's job is to provide sane defaults that are correct for the majority of people, not defaults that work for everyone or keep things as perfectly stock as possible. An example of this would be how we patch out duping exploits even though that caused plenty of questions. If Eigencraft is faster and keeps TPS higher for most people but means you can't build the 8-bit redstone computer, that's a fair trade.

**Comment by RoseFMoidel** [comment]
> > Definitely a hard no from me, this would make technical YouTube tutorials much harder to use and any redstone inventions you create would have a chance of only working on paper servers (And others with this engine) meaning broken redstone timings if you ever make your server vanilla again. Please leave it off by default.
> 
> This is why I would advocate that we experiment with Eigencraft because nobody can exactly quantify an example, at this point, showing where (if at all) Eigencraft breaks things. We first need to find (in my view) a place where Eigencraft breaks, and then determine how many builders would be affected.
> 
> Paper's job is to provide sane defaults that are correct for the majority of people, not defaults that work for everyone or keep things as perfectly stock as possible. An example of this would be how we patch out duping exploits even though that caused plenty of questions. If Eigencraft is faster and keeps TPS higher for most people but means you can't build the 8-bit redstone computer, that's a fair trade.

Ok, I really can't stress this enough, duping (of tnt at least) is not patched out, it's a setting in the CONFIG file, so I don't know, maybe your alternate redstone engine could be... A configuration option instead of something forced on everyone? That would be great.

**Comment by electronicboy** [comment]
Nobody has said that it would be forced on anybody, just that it's worth considering it being enabled by default, and then people can disable it, with a config.

**Comment by GabrielSieben** [comment]
> Ok, I really can't stress this enough, duping (of tnt at least) is not patched out, it's a setting in the CONFIG file, so I don't know, maybe your alternate redstone engine could be... A configuration option instead of something forced on everyone? That would be great.

I mis-spoke, that's exactly what I am trying to say. We have a configuration option for it, it is my opinion that more people would care for the performance benefits over the builds it would break (although nobody has, of yet, proven a single build as far as I am aware that would break other than just something "probably" would). For those who care about such builds that require such perfect Redstone behavior (maybe the 8-bit redstone computer wouldn't work?) it would be a setting to turn off.

**Comment by Malfrador** [comment]
Due to how often redstone computers are mentioned here I wanted to try it out. I tried [this redstone computer](https://www.youtube.com/watch?v=SbO0tqH8f5I&t=0s), which seems pretty advanced (8 bit, 4 cores, 32 bytes of ERAM and 3.702kb program memory).
All 4 included demo programs (fibonacci, multiplication, drawing a smiley face, random drawing) work absolutely fine with Eigencraft enabled on Paper-1.18-112 with otherwise default settings. 

Due to this I see absolutely no reason to not enable eigencraft by default. Its one of the first settings I always enable whenever I run a server, it measurably improves redstone performance and _if_ it breaks something (maybe some slime/piston contraptions?) it can be easily disabled.

**Comment by SpaceWalkerRS** [comment]
Speaking as an admin of a creative plot server that runs Paper where most players are redstoners, we tried enabling the Eigencraft patch some time ago. Before the end of the day, we had several dozen complaints about broken contraptions. HOWEVER, all but one of them was locational in the first place (meaning even in Vanilla they could break if built in a different location). That is the biggest change you will see with the Eigencraft patch (or Alternate Current, for that matter). Beyond that, I think there are very few things that will work outright in Vanilla but break with those alternate redstone implementations.

From my personal experience, redstoners that work a lot with redstone dust *will* notice, but I also recognize that that is a small subset of players. So in that sense, leaving such a patch on by default is fine.

One other downside I can think of is players building some contraption from a tutorial, and that contraption would fail because it is either locational or one of the rare cases that the patch breaks outright.

**Comment by RoseFMoidel** [comment]
> > Ok, I really can't stress this enough, duping (of tnt at least) is not patched out, it's a setting in the CONFIG file, so I don't know, maybe your alternate redstone engine could be... A configuration option instead of something forced on everyone? That would be great.
> 
> I mis-spoke, that's exactly what I am trying to say. We have a configuration option for it, it is my opinion that more people would care for the performance benefits over the builds it would break (although nobody has, of yet, proven a single build as far as I am aware that would break other than just something "probably" would). For those who care about such builds that require such perfect Redstone behavior (maybe the 8-bit redstone computer wouldn't work?) it would be a setting to turn off.

Ok, but most people I've talked to prefer vanilla redstone, and it being on by default would cause numerous issues, not the least of which is any server that UPDATES (or switches from vanilla) to a version of paper where the default redstone engine suddenly changes on them, it is going to make things BREAK. It should be an option, but It should be off by default.

**Comment by LaurenceBarnes** [comment]
as far as I understood what was suggested here, changing the default value does not necessarily need to mean that every value of existing configs will be changed, it just means that new configs will be generated with a different default value - which is totally fine. "[...] where the default redstone engine suddenly changes on them [...]" will just not happen that way.

**Comment by GabrielSieben** [comment]
Correct - my request is for that new configurations be generated with Eigencraft enabled by default so that brand-new servers get better performance.

For people making those new servers, how many brand-new servers will be created with niche Redstone mechanics in mind? Very few - and they'll know about it and turn Eigencraft off. For the rest, they can turn off Eigencraft if it ever comes up from the players - but if it doesn't come up, free performance. 

And for any server that already exists - the option for Eigencraft is already set to off in the default config they'd already have. No reason to overwrite that.

**Comment by LaurenceBarnes** [comment]
People caring about niche Redstone will likely choose a vanilla server anyway, and as far as I know, the commonly used carpet mod has Eigencraft code as well.

If I understood correctly though, you also suggest Alternate Current as an additional implementation? This one, while still true to certain mechanics, will not work with locational builds (which technically is a fixed inconsistency) from what I heard. However, the apparent boost it offers to performance might fit with what Paper aims to do and it would be great to have it. I personally think that in this case though, the arguments mentioned here against Eigencraft as a default definitely work.

**Comment by pop4959** [comment]
I've been using Eigencraft on my public server for a few years now, and have never received a major complaint from players about any contraptions not working. It really works amazingly well for what it is, being an alternative redstone implementation.

That being said, I still would prefer this not to be default. Why? Because even though it's awesome, there *are* possibilities for it to break things. Some examples have already been mentioned above.

Making this the default would go against a lot of people's expectations. Try to think in the head of an average user: you install Paper, now suddenly some contraption doesn't work. You don't know what Eigencraft redstone is, and you might not care. Now you have no clue what's wrong and are required to spend time trying to fix it, or give up and stop using Paper.

People who need or want optimizations can find them, and try them out. They'll also know what they've changed and be able to revert it if it causes issues. That's basically where I stand with this, since changing the default would only really benefit anyone too lazy to go through their config to turn it on.

**Comment by GabrielSieben** [comment]
> Making this the default would go against a lot of people's expectations. Try to think in the head of an average user: you install Paper, now suddenly some contraption doesn't work. You don't know what Eigencraft redstone is, and you might not care. Now you have no clue what's wrong and are required to spend time trying to fix it, or give up and stop using Paper.

I would argue that, in my perspective, this argument does not hold because we do things players don't always expect anyway. A perfect example is why we have the pinned https://github.com/PaperMC/Paper/issues/3854. You might have no clue why Bedrock isn't breaking or why you can't carpet dupe, as some of my own friends were confused by.

**Comment by pop4959** [comment]
> I would argue that, in my perspective, this argument does not hold because we do things players don't always expect anyway. A perfect example is why we have the pinned #3854. You might have no clue why Bedrock isn't breaking or why you can't carpet dupe, as some of my own friends were confused by.

I feel that is an aggressively political stance to take as to why Eigencraft redstone should be enabled. I would also not necessarily liken an alternative redstone algorithm to known bugs/exploits.

**Comment by RoseFMoidel** [comment]
> I've been using Eigencraft on my public server for a few years now, and have never received a major complaint from players about any contraptions not working. It really works amazingly well for what it is, being an alternative redstone implementation.
> 
> That being said, I still would prefer this not to be default. Why? Because even though it's awesome, there _are_ possibilities for it to break things. Some examples have already been mentioned above.
> 
> Making this the default would go against a lot of people's expectations. Try to think in the head of an average user: you install Paper, now suddenly some contraption doesn't work. You don't know what Eigencraft redstone is, and you might not care. Now you have no clue what's wrong and are required to spend time trying to fix it, or give up and stop using Paper.
> 
> People who need or want optimizations can find them, and try them out. They'll also know what they've changed and be able to revert it if it causes issues. That's basically where I stand with this, since changing the default would only really benefit anyone too lazy to go through their config to turn it on.

This. This has been my point from the start. It doesn't need to be on by default, and honestly shouldn't be for a number of good reasons.

**Comment by GabrielSieben** [comment]
I am aware that a change in implementation is not the same as repairing a known bug or exploit.

I disagree with the very premise of your argument: "think in the head of an average user: you install Paper, now suddenly some contraption doesn't work. You don't know what Eigencraft redstone is, and you might not care. Now you have no clue what's wrong and are required to spend time trying to fix it, or give up and stop using Paper."

According to almost everyone here who has commented on the use of Eigencraft, it is very reasonably to believe that you would have to be _very far beyond_ an "average user" to ever run into a situation where Eigencraft caused issues. Heck, even advanced users would be sometimes hard-pressed to find such a situation, as evidenced by @Malfrador 's successful use of an 8-bit computer build from Redstone in Paper without issue.

Therefore, your argument falls apart in that the average user has no situation where they would run into an Eigencraft issue - and if they did, they can find the issue just as every person who wants carpet duping enabled does right now. In my mind, the amount of people who would run into an issue with Eigencraft judging by the responses from this thread is identical or less than the amount of people upset over carpet duping being disabled by default.

**Comment by RoseFMoidel** [comment]
> > Making this the default would go against a lot of people's expectations. Try to think in the head of an average user: you install Paper, now suddenly some contraption doesn't work. You don't know what Eigencraft redstone is, and you might not care. Now you have no clue what's wrong and are required to spend time trying to fix it, or give up and stop using Paper.
> 
> I would argue that, in my perspective, this argument does not hold because we do things players don't always expect anyway. A perfect example is why we have the pinned #3854. You might have no clue why Bedrock isn't breaking or why you can't carpet dupe, as some of my own friends were confused by.

I would argue you aren't the only person running a paper server and are being far too pushy about what, in the end, is your opinion. You're entitled to your opinion, and your config file can reflect that (kinda what it's for, making your server the way you want it). Not everyone shares those opinions though, so I really don't see the logic of making it default for everyone. Chill dude.

**Comment by GabrielSieben** [comment]
Defaults exist to serve what the developers believe the majority of users would prefer, so that the amount of additional configuration required is minimal.

My argument stems from that I believe, judging by the responses of people who have tested Eigencraft here and elsewhere, that the vast majority of Paper users will never experience any problems with Eigencraft. They will instead benefit from additional performance, something that users frequently ask for. Anyone who disagrees or runs into an issue (which, anecdotally from this thread, would be very uncommon), can update their configuration file to reflect their use case. Kinda what it's for, making the server the way they want it.

If you can show that a reasonable mind would expect the majority of users would prefer to have very niche Redstone functionality at the expense of performance, or that Eigencraft breaks something that is not niche but would broadly affect Redstone builders, I'm open to having my mind changed. I have not seen anything in this thread to prove such an issue. Thus, I will continue my request that we make this a default as I firmly believe the vast majority of users would prefer performance, but I'm open to any discussion on how they would not prefer this.

However, I will not be open to any discussion which uses patronizing responses ("chill dude") and FUD tactics around new technology (as if Eigencraft breaks stuff left and right which is not the case) rather than claims from experience or other evidence. I will not engage in a bad-faith argument.

**Comment by pop4959** [comment]
I think you may have read over the entire argument I was trying to make. Let me clarify that the "average user" I am talking about is not the average redstone user (who will be unimpacted), but the average Paper user (e.g. server admins). Redstone users in the minority would be the ones complaining, and the Paper user may be unaware of the changes to default redstone, causing them much more trouble than if they were to opt-in. The real issue is the bad user experience that can result.

> if they did, they can find the issue just as every person who wants carpet duping enabled does right now. In my mind, the amount of people who would run into an issue with Eigencraft judging by the responses from this thread is identical or less than the amount of people upset over carpet duping being disabled by default.

This here pretty much proves much of my *actual* argument. There is a minority here which would be affected (in a way, which actually can be likened to the minority of users impacted by bug/exploit fixes) negatively by the change, and forcing them to either 1) waste their time to hunt down a config option they more or less don't care about, or 2) stop using Paper. This is fully unnecessary since it can be avoided by leaving the current default as-is.

> Defaults exist to serve what the developers believe the majority of users would prefer, so that the amount of additional configuration required is minimal.

This basically also leads into my point of "changing the default would only really benefit anyone too lazy to go through their config to turn it on." Also, where do you draw the line on this? There's a huge number of options in Paper, and anyone's "minimal" change to configuration will differ widely. Not to mention the costs associated with many options, which is why the safe default in almost all cases is to stick with fully vanilla behavior.

> Anyone who disagrees or runs into an issue (which, anecdotally from this thread, would be very uncommon), can update their configuration file to reflect their use case. Kinda what it's for, making the server the way they want it.

This can easily be turned on its head (anyone who has an issue with current redstone can turn Eigencraft on as an optimization).

I don't plan on arguing too much back and forth on this, but I still hold firm that ***unless an argument is provided proving that there is no negative impact of enabling this option*** it makes very little sense to change the default. The anecdotes are great and all, but they don't disprove anything.

Again, this is a change that only benefits those too lazy to enable the option. You need to go through the config to tweak everything else, so why exactly is this a grand exception?

**Comment by electronicboy** [comment]
Given my own inclinations on this and some of the commentary over the past few months, I err towards not changing this, our goal has generally always to be as close to vanilla as possible (outside of bugs), and I don't feel that that should change here

**Comment by DereC4** [comment]
bruh.
