### ISSUE TITLE
Bundle item with no Count value will crash the server

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7011]
### Stack trace

https://paste.gg/p/anonymous/69301b2ceeb24aada0da4cef2c1a6015

### Plugin and Datapack List

[00:51:20 INFO]: Plugins (0): 

[00:51:23 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[00:51:23 INFO]: There are no more data packs available

### Actions to reproduce (if known)

`/item replace entity @s armor.head with bundle{Items:[{id:"minecraft:stone"}]}` will crash, while
`/item replace entity @s armor.head with bundle{Items:[{id:"minecraft:stone", Count: 1}]}` will not.

### Paper version

[00:44:08 INFO]: Checking version, please wait...
[00:44:09 INFO]: This server is running Paper version git-Paper-391 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3e73355 on ver/1.17.1)
You are running the latest version

**Comment by lynxplay** [comment]
Thanks for the report :+1: Generally speaking, this is another issue that is purely caused through creative mode shenanigans or, well server commands. It is also related to https://github.com/PaperMC/Paper/issues/6550., as adding items to overfilled bundles causes the same issue of adding null/air.

This is only really resolved by removing the API check which comes with it own hassel.
I marked this as unlikely for now as this issue (or a form of it, see #6550) has been known for a while but was never really considered worth the trouble of fixing due to it being a direct result of command abuse / unobtainable items.

**Comment by e-im** [comment]
Thanks for your report; however, due to the immense number of places where this type of stuff may occur on servers that give everyone all perms, the maintenance cost of having fixes for all of this is more than it is worth. Please consider not giving all of your players op/all permissions, or, write restricted replacements for many of the vanilla commands as a plugin.
