### ISSUE TITLE
Get Num of Loaded Chunks

### ISSUE THREAD

**Issue by Rincewind34** [PaperSpigot/Paper#7099]
### Is your feature request related to a problem?

I'd like a low performance impact method to get the number of loaded chunks.

### Describe the solution you'd like.

Adding a method to World #getAmountOfLoadedChunks(). #getChunks().length does stuff, thats not needed if you only want the amount (mainly being not O(1) ).
I know that before 1.17 it was possible to access an integer directly in NMS. Looking at the current implementation that is not trivially possible anymore since the look up filters out certain values (null).

I'm not deep enough in the chunk loading process to point to one value in NMS and say: thats it and this value is aways right but maybe one of you guys has a good idea where to look.

### Describe alternatives you've considered.

Even if it turns out that its not possible to implement a low overhead way of doing it, adding the method anyway and implementing it with `return getChunks().length` would in my opinion still be worth doing for good software design. If someone in a feature comes up with an idea how to implement that more efficient or Mojang changes their code to make a O(1) implementation possible, the plugins can instantly benefit from the performance improvement.

**Comment by electronicboy** [comment]
There is no way to get the loaded number of chunks without iterating the entire loaded chunk list because you need to see if the chunks are actually at the correct level to be considered loaded, on that basis, I err on yet another method we have to maintain just for the general sake of it for something which if you cared about performance you could just maintain your own counter
