### ISSUE TITLE
Add an option to use Vanilla RNG instead of paper RNG

### ISSUE THREAD

**Issue by Infecta** [PaperSpigot/Paper#7166]
### Is your feature request related to a problem?

So a few of my friends wanted to do some RNG manipulation on our minecraft server but since we are running on paper we couldn't get our player seed and such.

### Describe the solution you'd like.

Add an option to choose between Paper RNG and Vanilla RNG in the paper.yml file

### Describe alternatives you've considered.

I tried compiling my own version that reverts it. I gave up.

**Comment by e-im** [comment]
Paper fixes exploits, this won't be done. There also isn't a "paper rng" and "vanilla rng", but, regardless, based on what you've said removing [this patch](https://github.com/PaperMC/Paper/blob/df8d28a450fe391b9f0c2dc4a64543cf9b84266f/patches/server/0070-Use-a-Shared-Random-for-Entities.patch) will likely do the trick.

To add, I've made a plugin which will revert this change https://modrinth.com/plugin/randomcontrol

**Comment by EvModder** [comment]
> Paper fixes exploits, this won't be done.

Not everyone shares your definition of an "exploit", it's a bit pretentious to assume your ideal framework of gameplay is the same universally.

> There also isn't a "paper rng" and "vanilla rng"

From reading the patch's code, it seems pretty clear that sharing a random seed between all entities is a pretty different interpretation of RNG compared to vanilla.

I honestly feel like this was closed too hastily without due consideration, since this mechanic is something a lot of players might want to utilize. The advise for OP to just "remove that patch" is not very broadly applicable, since some server owners will lack the technical knowledge, and others such as myself simple would prefer to avoid the hassle of having to rebuild the Paper project each time there is an update with a custom maintained fork that just changes one thing (especially when it's something that would be really easy for Paper to just add a config setting for).

I'd happily volunteer to send a PR which adds this as a config setting, if I had any assurance the authors of the Paper project might approve it. I always thought Paper liked to advertise itself as "the more vanilla alternative to Spigot" but I guess that distinction has diminished over time.

**Comment by clrxbl** [comment]
> I always thought Paper liked to advertise itself as "the more vanilla alternative to Spigot"

This has never been the case.

**Comment by EvModder** [comment]
> 

Depends who you ask; back in the ancient times (before Bukkit collapse) I would see paper advocates on the Spigot forums talking about how the biggest benefit of Paper was that you got all the optimization of Spigot but maintained a more vanilla experience; you very well might be correct to assume this is no longer the case, but it still seems to be a prevalent mindset--e.g., I did a quick google search and found a guy on r/Admincraft from a few months ago claiming Paper was more vanilla than Spigot in response to a question of which to prefer.

Either way, it does not feel relevant to the original FR.

**Comment by lynxplay** [comment]
really falls into the same niche as sand duplication.
We don't offer a configuration option for it, but there are plugins you can use to enable the "feature"/exploit again.
See https://modrinth.com/plugin/randomcontrol.

**Comment by Machine-Maker** [comment]
>  claiming Paper was more vanilla than Spigot

I think this is true now. But that being true does not mean that Paper has billed itself as "as close to vanilla as possible".

**Comment by electronicboy** [comment]
Paper fixes bugs, the side-effect here is that a bug fix had broader implications down the line as people figured a way to abuse it a while later;  while we also fix inconsistencies induced by upstream, and even things people consider inconsistent in vanilla itself, at least from the realms of most server owners, there's 0 promise around niche/exploitative mechanics.

I've debated adding config options however, any time I've gotten close to actually finding the time and political will to fight for it, there's generally been somebody who goes scorched earth on me and I figure not to bother fighting "for the cause".

**Comment by EvModder** [comment]
Thank you for the plugin link @lynxplay, and @electronicboy for the explanation; based on reading the aforementioned sand-dupe chain of bugs and discussion I can see there is a precedent for this sort of thing to *not* have a config option, which is a bit discouraging but I somewhat understand where those people are coming from.

Please know that your contribution efforts are appreciated, and there will always be people out there grateful for any hard-fought configuration control, even if it feels unrecognized :)

**Comment by SuperSerferNow** [comment]
can you update it to 1.21.4
