### ISSUE TITLE
Lag when opening a shipwreck chest containing buried treasure map

### ISSUE THREAD

**Issue by FastJoe0** [PaperSpigot/Paper#7269]
### Stack trace

```
https://paste.gg/p/Oamo/e956e78698554d46b2f356889e32140c
```

### Plugin and Datapack List

none

### Actions to reproduce (if known)

1. Type /locate shipwreck
2. Teleport to the place indicated by the command.
3. Open the chest in the shipwreck
4. If the chest has a buried treasure map a big lag will appear.

### Paper version

This server is running Paper version git-Paper-132 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5e30e19)

**Comment by FastJoe0** [comment]
I have updated actions to reproduce.

**Comment by electronicboy** [comment]
This is a vanilla issue in which the search logic for finding features, etc, basically starts running through a huge radius; This is an issue which we've chased consistently back and forth over the years for mojang to 'fix it', breaking our existing patches and such; pregen'ing can help with all the stipulations that induces, but, I'm inclined to believe that this should be replicated on vanilla and sent to them rather than us getting stuck in this consistent cycle of fighting with them over this more or less

**Comment by FastJoe0** [comment]
But it causes the server to crash completely in some cases. Is it possible to somehow block the buried treasure map item so that it doesn't appear in these chests?

**Comment by electronicboy** [comment]
Yes, you can use a datapack to override the loot for those chests to remove it
We know that it causes issues but we've rewritten the patch for this like 3 times over the past 5 versions, I do not feel that there is much inclination from us to further spend any time wasted on this, it's not a maintainable patch as mojang keeps messing with this

**Comment by FastJoe0** [comment]
Or maybe you will add at least options in paper.yml to disable these maps. If anyone wants, let them use them at their own risk.

Datapacks are not easy to remove from the map in case of problems.

**Comment by electronicboy** [comment]
We're not mangling data using config options, use a datapack, there was one floating around and am sure somebody can make one

**Comment by Pantera07** [comment]
https://github.com/PaperMC/Paper/commit/6697ce361e63e9a7bcacff95847f8a073d64fce5
Required but deleted optimizations :(

**Comment by ryantheleach** [comment]
@FastJoe0 Datapacks that change loottables should be trivial to remove without side effects.
