### ISSUE TITLE
Treasure map bug

### ISSUE THREAD

**Issue by BabyWaffles** [PaperSpigot/Paper#7349]
### Expected behavior

The treasure map will always show the first looted treasure chest despite "treasure-maps-return-already-discovered" is still set to false

### Observed/Actual behavior

The first 1200 blocks every side of the shiprack's treasure map will point to the first treasure map chest.

### Steps/models to reproduce

Find the first treasure map to generate the first treasure loot then find another new treasure map.

### Plugin and Datapack List

Normal 1.18-paper-152.jar

### Paper version

This server is running Paper version git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)
You are running the latest version
Previous version: git-Paper-68 (MC: 1.18.1)

### Other

That's all.

**Comment by lynxplay** [comment]
I can replicate this. I am hesitant to currently mark this as accepted, as this behavior (at least judging from the source) stayed the same since its initial implementation. 

Vanilla has a similar concept in its loot definitions which governs over ignoring existing chunks and for each of the three loot tables (shipwreck as well as big and small underwater ruin) it is explicitly set to `false`.

The paper config option does not overwrite this but would only overwrite things when set to `true`.
This may hence very much be the intended behavior, however I do not remember if it was so I will not move this issue further then removing the need for triage.
