### ISSUE TITLE
keepInventory gamerule only works in over world

### ISSUE THREAD

**Issue by ifloppy** [PaperSpigot/Paper#7463]
### Expected behavior

keepInventory works on all of the dimensions

### Observed/Actual behavior

keepInventory gamerule only works in over world

### Steps/models to reproduce

enable keepInventory,teleport to the end dimensions, execute /kill

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/68799904/153408459-17f2964c-a698-4601-a017-6e99641eb3a9.png)
![image](https://user-images.githubusercontent.com/68799904/153408484-3c76d00f-4772-4498-8b66-3b388249dafd.png)

### Paper version

> version
[20:28:00 INFO]: This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are running the latest version

**Comment by electronicboy** [comment]
Game rules are per world, you'll need to use the game mode command in each
world

**Comment by ryantheleach** [comment]
@ifloppy For what it's worth, this is an intentional break from vanilla behavior by craftbukkit years back.

It's to allow gamerules to be changed in alternate 'universes' or if your server wanted to make the nether harder or something.

It's always been a pet-peeve of mine that the commands don't act like the vanilla ones (and has caused angst in the Minecraft Command Datapack communities), but I respect the need to make it per-world.

I'd advocate for the commands to make the changes globally, but it's simply been this way too long in craftbukkit IMO.

I'd welcome suggestions though to restore Vanilla parity, that doesn't make it too confusing to users, e.g. change the commands to act on all dimensions unless the world is specified, with a warning in chat?

Or maintain the existing craftbukkit behavior, and change the command output to clearly state that it's changed the gamerule in ONLY THIS DIMENSION.

I've been burnt by this as a server admin in the past, when trying to configure gamerules that I expected to apply globally to the nether etc, it sucks when players die in the end, and lose all their stuff, when they had been playing on a server for the last month with keep inventory on.

**Comment by metolone** [comment]
If I set "gamerule keepinventory true" on the paper server, it only sets in the overworld.  How do you set it for the never (or the end?) from the server console?

I've been burnt multiple times with this and thought it was a bug until today when I looked at the bug list.

**Comment by Machine-Maker** [comment]
From the console, you should use the `execute in minecraft:<world> run <command>`. You can also do that as a player to run a command in another world.

**Comment by metolone** [comment]
@Machine-Maker Thanks...pretty new to running a server and the commands.
