### ISSUE TITLE
Cursed books won't stack

### ISSUE THREAD

**Issue by jayrock3000** [PaperSpigot/Paper#7484]
### Expected behavior

Combining two cursed books in a grindstone should make a stack of two books which a player can shift click to pull into their inventory.

### Observed/Actual behavior

Recipe flashes correctly for a split second, then cancels out and doesn't allow you to combine the books.

### Steps/models to reproduce

Place two curse of binding books into a grindstone

### Plugin and Datapack List

none

### Paper version

This server is running Purpur version git-Purpur-1492 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 29b24bc on HEAD)
You are 69 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous version: git-Pufferfish-17 (MC: 1.18.1)

**Comment by electronicboy** [comment]
You're not running paper

**Comment by willymv** [comment]
Recreated on a fresh Paper 205 server. I also checked to the latest Spigot 1.18.1 from BuildTools and this issue is not present.

(Paper)
![2022-02-20_15 15 32](https://user-images.githubusercontent.com/94822136/154828286-3a9e4a1d-b419-4f8f-bc75-836d452c7ee0.png)

(Spigot)
![2022-02-20_15 19 40](https://user-images.githubusercontent.com/94822136/154828309-6290d350-9524-4fb6-98c2-ac634e54c28f.png)

**Comment by Machine-Maker** [comment]
This is an intentional fix by paper to respect item max stack size in the grindstone output. See [this patch](https://github.com/PaperMC/Paper/blob/79dd62ae620c082646b2f376451cceb52d3b4618/patches/server/0609-Prevent-grindstones-from-overstacking-items.patch).

EDIT: Confirmed as bugs [here](https://bugs.mojang.com/browse/MC-157133) and [here](https://bugs.mojang.com/browse/MC-140397)
