### ISSUE TITLE
PaperMC breaks Iron Golem Farm

### ISSUE THREAD

**Issue by GNUGradyn** [PaperSpigot/Paper#7488]
### Expected behavior

Iron Golem farm (the design with Villagers spawning iron golems that fall into lava) should spawn an iron golem every 30 seconds

### Observed/Actual behavior

It works properly for ~10 minutes then slows to a crawl

### Steps/models to reproduce

1. Build a Villager based iron golem farm. Paste this schematic if unsure
[spawner.zip](https://github.com/PaperMC/Paper/files/8101455/spawner.zip)

Observe it functions as you'd expect spawning an iron golem every 30 seconds

2. Wait 10 minutes or so

Observe it will now rarely spawn more iron golems

### Plugin and Datapack List

Only plugin is FAWE which I used to paste the schematic. No data packs

### Paper version

This server is running Paper version git-Paper-203 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5bb4549)
You are running the latest version
Previous version: git-Paper-101 (MC: 1.18.1)

**Comment by rydarj** [comment]
Having this same issue. Works for a few minutes, only way I get it to work again is blocking the villagers vision at night while they try to sleep. 
The farm im using works perfect in singleplayer.

**Comment by ghost** [comment]
Can also reproduce with this Design from JWhisp: https://www.youtube.com/watch?v=UWE-tgK9HDY, only way to fix is to wait for the farm to start working again, or to set time to night, and then they try to sleep and fine. Works until unloaded, then breaks again.

EDIT: You can also try a Zombie Villager In Leiu of a Zombie, same issue.

**Comment by MrTransistorsChannel** [comment]
Have just updated the server from Paper-182 to Paper-215 and iron farm stopped working. The reason it stops is that villagers *need to sleep* to be able to generate golems, but after update they can`t go to bed and are just standing and constantly producing green particles like when they are claiming the bed.
![2022-02-26_19 37 47](https://user-images.githubusercontent.com/34776474/155851257-dac1d622-fa0c-4435-8db3-23ccf74245c8.png)
The farm was designed by myself, last tested Paper version is 182 where it works just fine, will try to check versions between 182 and 215 and provide additional info.

**Comment by MrTransistorsChannel** [comment]
After some testing found that my problem cannot be reproduced, also if I go back to the version 182 villagers still can't sleep.
The only way to fix the issue in my case is to manually replace all the beds, I think it relates to some data in the world save that keeps track of the claimed beds because all of the villagers don`t have "minecraft:home" tag in their Brain{memories:{}}. Will have to try this again on a backed up world.

**Comment by ghost** [comment]
Seems to be some designs, I switched up from the design by JWhisp to a design I came up with for my realm a couple of years back, similar design to the op here, except I changed the kill chamber, and have floating platforms. Once I changed design Ive had no issues, farm produces as much iron as expected. OP, Try this video: https://www.youtube.com/watch?v=hGDdUJC-0dA and see if you have the same issues, I don't do the Soul sand on the block below, and it works fine. You could also try switching the soul sand for a regular block, its only needed in some scenarios

**Comment by iwa** [comment]
i had the issue on 1.18.2 (latest build - 324)
idk why but it seems that one upgrade of paper bugged one of my villager in my farm, and they weren't sleeping, blocking the farm
it affected only one of the 3 villagers i have so idk why, but killing them and respawn them with new beds seems to fixed the issue for me

**Comment by Warriorrrr** [comment]
I'm unable to reproduce this issue, as the schematic you provided also does not seem to be a working farm; the villagers have constant line of sight with the zombie which prevents them from sleeping. After replacing the soul sand and trapdoors with solid blocks and removing the slabs, villagers sleep normally and iron golems start spawning. The beds also have occupied permanently set to true in their nbt data, which also prevents villagers from sleeping, replacing the beds fixes that.

The observed behavior is likely caused by the issue described above, since villagers need to have slept in the last 20 minutes in order to want to spawn a golem.
