### ISSUE TITLE
Chunkloading terrible in nether/end

### ISSUE THREAD

**Issue by agoniaprivat** [PaperSpigot/Paper#7516]

**Comment by electronicboy** [comment]
> Version | git-Purpur-1565 (MC: 1.18.1)

**Comment by agoniaprivat** [comment]
> > Version | git-Purpur-1565 (MC: 1.18.1)

But hey?

This issue happend on paper, tried switching to purpur to see if there was some diffrences?
As you can se, server is running paper version git-Paper-215 (MC: 1.18.1)

**Comment by electronicboy** [comment]
You provided a timings report from the wrong software, which does not line up with the picture you showed, and probably not the video you showed; I'm not going to try and decode what all lines up and what doesn't, if you wanna provide info, we want them linked together, i.e. a timings report produced right after the video or whatever, otherwise we're wasting our time

**Comment by agoniaprivat** [comment]
> You provided a timings report from the wrong software, which does not line up with the picture you showed, and probably not the video you showed; I'm not going to try and decode what all lines up and what doesn't, if you wanna provide info, we want them linked together, i.e. a timings report produced right after the video or whatever, otherwise we're wasting our time

My bad, took wrong report. Im updating this straight away.

Timings: https://timings.aikar.co/?id=d476456b4aaf4c8ca24ed672c0f3608f
Updated video: https://youtu.be/anKwcsswMa8
