### ISSUE TITLE
Hide cave_air to prevent cheating

### ISSUE THREAD

**Issue by KioProject123** [PaperSpigot/Paper#7531]
### Is your feature request related to a problem?

Some cheating clients can detecting the Cave Air block to find structures.
such as [CaveFinder](https://wiki.wurstclient.net/cavefinder)

### Describe the solution you'd like.

Replace all Cave air blocks sent to players with Air blocks

### Describe alternatives you've considered.

Maybe not

**Comment by ryantheleach** [comment]
Having this feature would have made debugging an issue in a plugin very very difficult.

I recently ran into an issue with a plugin, where something being built wasn't being detected in some structures.

It was because our check for air, didn't involve the concept of cave_air.

Hiding cave_air from the client, would have made this much much harder to debug, as we never would have known about it's existence.

Strong opposition from me, unless it's a disabled by default, or an option of the anti-xray configuration.

**Comment by Pantera07** [comment]
I think it could be a good feature like anti-xray, hide-itemmeta. (If this feature does not affect server performance)
