### ISSUE TITLE
Barebone Mode

### ISSUE THREAD

**Issue by nicecraftz** [PaperSpigot/Paper#7546]
### Is your feature request related to a problem?

This feature is needed for developers or even server owner who just want to test plugins or developer who need to test their code in action and have bad hardware

### Describe the solution you'd like.

barebone mode, useful for developers and server owners with not-so-fast computers, could be useful in some cases, barebone mode will set every setting at its minimum, or can be set in barebone config or something idk you choose, with this mode you just have the essentials, a world with a small world border like 200 blocks or something, no mob spawning no fire ticks y'know all game rules that can optimize performance toggled and every paper/spigot/bukkit setting at its minimum, idk could be useful even tho you can do it by actually applying this edits manually, its kinda painful to do it each time, also while this feature is on you could maybe apply some more optimization in the code?

### Describe alternatives you've considered.

This can be achieved manually by editing the configs but its slow and kinda painful  doing it everytime you need it but maybe the paper team can implement some optimization just for this feature. also a command to analyze in depth memory usage etc, other than timings which are already SO USEFUL but y'know to spice things up

**Comment by Grabsky** [comment]
While I see something like that would be useful in some cases, I can also tell that there is no universal solution for that.

Different plugins reqiures different scenario to be tested in. For example plugins that are built on top of vanilla world and mechanics (eg. random teleport or anything that manipulates environment on larger scale) wouldn't really work with said 200 blocks-wide world. Certain plugins would also require certain options to be turned on in configuration files. This is all up to the plugin you want to test, and you usually want to test it in an actual server environment.

System like that could only allow for testing basic features like commands, messages, permissions and everything not heavily-dependent on actual game machanics.

If it's worth your time, you can always write a server deploy script with pre-configured files and map, but usually you want to have a local server somewhere on your disk which is used only for testing pourposes and configuration is modified on the go, all dependend on what you're currently testing.

**Comment by electronicboy** [comment]
Thi just sounds like a lot of work for basically 0 gain for 99.999% of people

java already has tools for analysing memory usage of which is basically useless for the majority of server owners and far too in-depth of a goal which would basically be a project of its own, stripping down the server is nuanced because then you get into people who want to be able to configure what is stripped down, how do you apply the way this mess overrides the standard behavior, what tweaks are acceptable, i.e. are you not gonna break tweaking doing that, what is minimum? minimum allowed, minimum to be an actual usable testing environment? etc, etc, etc

far too wide of a scope scope, massively nuanced, for little gain for us or the wider community
