### ISSUE TITLE
minecraft.nbt.place does not work

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperSpigot/Paper#7618]
### Expected behavior

In creative mode players should not be able to place blocks that have nbt tags if they don't have the `minecraft.nbt.place` permission

### Observed/Actual behavior

The `minecraft.nbt.place` permission does not work, in creative mode players can place nbt items regardless of whether they have the permission. I have tried negating this permission but that doesn't stop players from placing items that contain nbt such as chests for example.

### Steps/models to reproduce

Set server gamemode to creative
Place a chest and fill it with blocks
Copy the chest with middle click and place the chest

### Plugin and Datapack List

No plugins

### Paper version

This server is running Paper version git-Paper-237 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: https://github.com/PaperMC/Paper/commit/b55ba19ad321c3dfe5589ffd016aa2847101e55a)

### Other

I don't think `minecraft.nbt.copy` works either but I have not tested that

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/server/0257-Allow-chests-to-be-placed-with-NBT-data.patch

**Comment by SecretlyJealous** [comment]
Sorry I'm a little confused, why was that patch introduced when a bukkit permission already exists for this behaviour? 
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/4165cd8f453f050e18a891297e2f00704e0b379d#CraftBukkit-Patches/0100-Add-creative-mode-NBT-permissions.patch

**Comment by electronicboy** [comment]
Because it doesn't exist for this vanilla behavior, the patch covers the ability to grant placement perms to stuff which doesn't allow it by default, it can't negate cases where they can place it, which is what your complaint is here

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/a2d26409f702f712525260ab6eddcfc49cf58d50#nms-patches/net/minecraft/world/level/block/entity/TileEntityChest.patch - placement of chests with NBT is a vanilla feature which upstream disabled which was restored in paper many years ago, I think in part there was a case which plugins or something wanted to use it which was broken

**Comment by SecretlyJealous** [comment]
Ah I see, thanks for explaining that
