### ISSUE TITLE
WorldGuard blacklist not able to block a PlayerInteractEvent using a glow ink sac

### ISSUE THREAD

**Issue by JacksonWillford** [PaperSpigot/Paper#7633]
### Expected behavior

When I added the glow ink sac to the WorldGuard blacklist.txt file with an on-use=deny argument, players would be unable to make signs and item frames into glow signs and glow item frames. The following configuration was used:
`# Deny Glow Ink Sac Use
[Glow_Ink_Sac]
on-use=deny,tell
message=Don't use ink sacs`

### Observed/Actual behavior

Players are still able to use glowing ink sacs to create glowing signs and glowing item frames. When using the configuration listed above, the message still displays; however, the use of the glow ink sac is not being cancelled.

### Steps/models to reproduce

1. Add the following to a blacklist.txt file for a world in WorldGuard:
`# Deny Glow Ink Sac Use
[Glow_Ink_Sac]
on-use=deny,tell
message=Don't use ink sacs`

2. Try changing a sign to a glowing sign by right clicking it with a glow ink sac and it the sign will change to a glowing sign.
- The denial message still displays https://i.imgur.com/6mxOsTj.png

### Plugin and Datapack List

This is reproduceable using the latest versions of WorldEdit and WorldGuard:
WorldEdit 7.2.9
WorldGuard 7.0.7

No datapacks

### Paper version

[19:59:56 INFO]: Checking version, please wait...
[19:59:57 INFO]: This server is running Paper version git-Paper-264 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a686ff5)

### Other

I hopped into the EngineHub discord for support of this issue, but it appears that the issue actually is with Paper. Looking into the WorldGuard code a little bit, it appears that the modification of the PlayerInteractEvent to deny to action isn't being respected. I am opening this incident on their recommendation.

**Comment by lynxplay** [comment]
I am having trouble re-creating this. I am sadly not too versed in the world guard source code, however the rather plain test-case
```java
@EventHandler
public void on(final PlayerInteractEvent event) {
    final ItemStack item = event.getItem();
    if (item == null || item.getType() != Material.GLOW_INK_SAC) return;
    event.setUseInteractedBlock(Event.Result.DENY);
}
```
properly prevents any interaction using a glow ink sac, including making a sign glow.

It would really help if you can create a proper reproduction step list instead of just pointing towards world guard.

**Comment by wizjany** [comment]
the thing being used here is the ink sac, so WG sets `setUseItemInHand(DENY)`. I guess your result shows that the sign is eating the ink sac instead of the ink sac dying the sign, which would be par for the course of bukkit being a terrible abstraction layer for mojank logic.

edit: also would like to add that the report states they're able to create glowing item frames as well - that doesn't seem to be the case. entity interaction events only have normal(full) cancellation, not the weird useitem/useblock split, so it's not affected by my testing.

**Comment by lynxplay** [comment]
Thanks for the entity info! In regards to the bukkit abstraction, on mojang level it is also the sign block that consumes a glow ink sac on interaction. I see your point tho, one would think (at least in concept) it is the glow ink sac that is being applied and hence it should be the one executing logic etc, tho this is sadly not the case on any level of the server.

Concerning that changing this is rather impossible without introducing our own logic and breaking the current behavior I will close this issue. I hope you guys can find a nice workaround but I do not believe that this is a paper issue (as always alternative opinions appreciated to keep this issue alive/reopened :sweat_smile:)
