### ISSUE TITLE
Memory leak at "PlayerChunkMap" "QueuedChangesMapLong2Object"

### ISSUE THREAD

**Issue by linsaftw** [PaperSpigot/Paper#7640]
### Timings or Profile link

https://timings.aikar.co/?id=0acd4ff33f15410c9c01bf5e9c628d67

### Description of issue

When running Paper 1.18.2 on a big server environment it seems like some chunks are being kept on this "queue" after they were unloaded from the server.

This might be related to (https://github.com/PaperMC/Paper/issues/4816) but I am not sure. Here i am posting more data that seems to indicate that some "unloaded chunks" are not being removed from this queue.

I am experiencing this weird behaviour too. (No players connected and chunks start loading/unloading)

![image](https://user-images.githubusercontent.com/25271111/159189479-baf25126-7248-4d63-a52d-17f4cc0cf964.png)

This are images of some information I seeked from the profiler.

![image](https://user-images.githubusercontent.com/25271111/159189224-27c814be-b291-4390-a682-e1b6b016f981.png)

![image](https://user-images.githubusercontent.com/25271111/159189229-922e4182-5100-440d-b214-f00591723c18.png)

![image](https://user-images.githubusercontent.com/25271111/159189237-f207fb20-eabf-4a40-bc85-9bc6c01afb7b.png)

### Plugin and Datapack List

Essentials, LiteCombat, Milks ViaRewind, ViaVersion, WorldBorder

### Server config files

https://paste.gg/p/anonymous/8b78d3f3eeee4ea3b02f2046355eb14c

### Paper version

This server is running Paper version git-Paper-265 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 993f828)

**Comment by minhh2792** [comment]
What is the profiler software you using ? (2nd picture)

**Comment by linsaftw** [comment]
> What is the profiler software you using ? (2nd picture)

Eclipse Memory Analyzer

**Comment by apatuka** [comment]
Hello @linsaftw did you find any workaround for this ? we have the same problem. The MAT dropped the same output as yours.

**Comment by linsaftw** [comment]
> Hello @linsaftw did you find any workaround for this ? we have the same problem. The MAT dropped the same output as yours.

Nope. Minecraft new chunk system is extremely hard to understand for me.

**Comment by LittleHed** [comment]
Same problem exists in the latest paper version

**Comment by electronicboy** [comment]
I've managed to reproduce something like this *once*, wasn't a leak either, was fluids basically doing stupid stuff like loading chunks, which, for that case, am not sure that there is a too sane way to deal with without potentially breaking fluid stuff...

**Comment by RealFinePoint** [comment]
Currently having this same issue. Has anyone found a fix yet?

**Comment by Akiranya** [comment]
I have this issue too. Memory leak at "PlayerChunkMap" "QueuedChangesMapLong2Object"

**Comment by ZeroedByte** [comment]
I too am having this issue. Keeps crashing my server with only two users on it with 8gb of memory allocated, 
![report202842562693091_Page_2](https://user-images.githubusercontent.com/45803051/187826090-b5c6402e-a82d-4679-8ee1-d18aca16ad0e.jpg)
![report202842562693091_Page_1](https://user-images.githubusercontent.com/45803051/187826091-f6ac34dd-02a3-4a83-8194-6e3e129ef889.jpg)

**Comment by electronicboy** [comment]
leak suspect reports are literally useless, "the chunk system uses a bunch of memory" is generally not inherently a leak and no surprise that a system which stores large transient data in memory, has a good chunk of memory in ram;
2194 chunks loaded on a server is not really all that much especially considering the new chunk system;

I'm honestly inclined to close these types ofissues, especially after the fixes made to the chunk system a while back such as ensuring that chunks will unload more aggressively when the chunk unload queue gets too high, otherwise, we'd need much more info, and there's already discussions elsewhere around this topic of which has generally gotten nowhere too, it generally seems to be an isolated issue rather than something which is blowing up for everybody, and in my own cases where I've monitored stuff blowing up, I've generally always been able to find an environmental cause which is not trivial to solve (and often self induced)

**Comment by linsaftw** [comment]
Sorry to not mention that this chunks were never unloaded after multiple minutes.

**Comment by RealFinePoint** [comment]
Well, I do have an update for this.
It was indeed a garbage collection issue and after tweaking the JVM flags
and updating to the new chunk system we've had zero crashes.
So, at least for me, consider this solved.

**Comment by MiniDigger** [comment]
thanks for the update, ill just close this then and of something new comes up, we can investigate again (will be different thanks to the new chunk system anyways)
