### ISSUE TITLE
Redstone with pistons is broken

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7725]
### Expected behavior

Pistons will work as they should

### Observed/Actual behavior

Some or all pistons can stuck/freeze in 'opened' state

### Steps/models to reproduce

Built this or just load [this](https://github.com/PaperMC/Paper/files/8458922/t.zip) structure into world:

![image](https://user-images.githubusercontent.com/19989717/162617561-95b0af90-1902-4e68-8d15-c9a5f9897ad6.png)

It it wasn't running, press stone button once. **In rare cases it works fine as it should.**
Try to build/load it at different places/positive or negative x/z and heights.

### Plugin and Datapack List

None,  just like `null`.

### Paper version

It's a downloaded jar from https://papermc.io/downloads and clean start, with every configuration file are default.
`use-faster-eigencraft-redstone` = `false`

```
This server is running Paper version git-Paper-283 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f8e8d6c)
```

### Other

So... after filling this issue I was checked it in vanilla singleplayer, and can confirm that this is a vanilla bug :/

**Comment by SpaceWalkerRS** [comment]
This is not a bug with Paper/Eigencraft. It is normal Vanilla behavior, as a consequence of three things:

1. Quasi-connectivity.
2. The range in which blocks are updated around redstone components.
3. The location dependent order in which blocks are updated around redstone wire.

Quasi-connectivity (QC) affects pistons, droppers and dispensers. It is the property that allows these blocks to accept power from diagonally above or two blocks directly above. It may help to think of these blocks as the bottom half of a door. If you power the (imaginary) top half, the bottom half will consider itself powered as well. 

Redstone was not really implemented with QC in mind. Most redstone components do not emit block updates in a large enough range, leaving any QC-powered pistons unaware of the power change until they are otherwise updated (e.g. by a block being placed next to them).

As if that isn't confusing enough, redstone wire updates the blocks around it in a location dependent order. This means you must be extremely careful when using it, because any sensitive contraptions might behave differently or break in different locations.

In the setup you built, the pistons are not only directly powered by the redstone wire directly above them, but also QC-powered by the two wires diagonally above them. Depending on the location of the setup, each redstone wire will update the blocks around them in a different order, and if you are unlucky, this happens in such a way that a piston is not updated after the wires that QC-power it turn off, and it will remain 'stuck' extended. 

The effect that Eigencraft has (and Alternate Current will have, too) is that this behavior is no longer location dependent. Instead, each setup will behave the same in every location it is built. Eigencraft and Alternate Current will not necessarily behave the same as each other, though. Eigencraft has chosen to introduce an element of randomness in cases where direction of information flow is ambiguous, while Alternate Current takes the route of leaving in an element of direction dependency. What this means is that there are very rare setups that will behave randomly with Eigencraft, while with Alternate Current they will behave differently depending on the orientation in which they were built.
