### ISSUE TITLE
unable to take the result after using PrepareAnvilEvent#setResult after build 288

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7783]
### Expected behavior

I should be able to take things out of the anvil

### Observed/Actual behavior

I can't take things out of the anvil

### Steps/models to reproduce

Add this code somewhere to your plugin:
```java
public void onAnvil(PrepareAnvilEvent e) {
    e.setResult(new ItemStack(Material.STONE));
}
```

### Plugin and Datapack List

Plugins (1): TestPlugin

[20:36:31 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[20:36:31 INFO]: There are no more data packs available

### Paper version

[20:36:40 INFO]: Checking version, please wait...
[20:36:40 INFO]: This server is running Paper version git-Paper-317 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e5da93a)
You are running the latest version
Previous version: git-Paper-313 (MC: 1.18.2)

### Other

Using build 288 works fine, anything after that is completely broken. I think build no.289 is the problem

**Comment by Doc94** [comment]
For me i test this in spigot/paper and can take the item, but only if set a item in the first slot...
in this case (only click the slot) this not work.
![image](https://user-images.githubusercontent.com/3602279/166173413-3c412d82-911b-4dd1-abbe-a15880d307e2.png)

and the issue its.. because in this case the cost its -1 based in the change in upstream https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/b5559f8c4d6a23db218c1071f95e9314c82d4010 then for this case you need try validate the repaircost and if is -1 set to 0 for keep the old logic.

**Comment by u9g** [comment]
> For me i test this in spigot/paper and can take the item, but only i try change a item first... in this case this not work. ![image](https://user-images.githubusercontent.com/3602279/166173413-3c412d82-911b-4dd1-abbe-a15880d307e2.png)
> 
> and the issue its.. because in this state the cost its -1 based in the change in upstream https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/b5559f8c4d6a23db218c1071f95e9314c82d4010 then for this case you need try validate the repaircost and if is -1 set to 0 for keep the old logic.

So how do I make this work for my example like it used to?

**Comment by kennytv** [comment]
`event.getInventory().setRepairCost(0);`

**Comment by Doc94** [comment]
Yeah something like
```java
public void onAnvil(PrepareAnvilEvent e) {
    e.getInventory().setRepairCost(0); // Make all free
    e.setResult(new ItemStack(Material.STONE));
}
```
