### ISSUE TITLE
Non-Enderman MOB spawns in The End.

### ISSUE THREAD

**Issue by NamiUni** [PaperSpigot/Paper#7810]
### Expected behavior

No MOB spawns at The End except for Enderman.

### Observed/Actual behavior

MOBs other than Enderman spawn at The End.

### Steps/models to reproduce

1. Start a Paper server with this world
[world_the_end.zip](https://github.com/PaperMC/Paper/files/8666207/world_the_end.zip)
2. Teleports to The End coordinates x100 y100 z300
3. MOBs other than Enderman spawn on this MOB farm.
![2022-05-11_11 18 50](https://user-images.githubusercontent.com/53502121/167756955-b442362a-4f37-42a8-972d-d93f022e915b.png)

### Plugin and Datapack List

Plugins (2): Chunky, WorldEdit
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-330 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 268476b)

### Other

This farm was moved from another location using world edit.

**Comment by e-im** [comment]
This is caused by an incorrect biome at that location. In your world, this is most likely due to an unfortunate bug in very early paper 1.18 builds that wrote the wrong biome in the end. You've got two options:

A. Fix with the WorldEdit biome command
B. Install a [https://github.com/NoahvdAa/EndBiomeFixer] dedicated plugin to automatically fix the issue everywhere.

**Comment by NamiUni** [comment]
#7125 duplicate. My apologies!
Thanks sulu!!!
