### ISSUE TITLE
Subspace Bubble unlocks in all overworlds

### ISSUE THREAD

**Issue by Podgorica** [PaperSpigot/Paper#7953]
### Expected behavior

The "Subspace Bubble" advancement should not work with all overworlds and/or nethers so as to be consistent with "Uneasy Alliance" and "Feels like home" advancements requiring the default "world" the Overworld to unlock.

As per issue #7809 there is only one Overworld (proper noun, spelled with a capital O, not a world that looks like it) and this advancement should only unlock when returning to `minecraft:overworld`.

### Observed/Actual behavior

The "Subspace Bubble" advancement unlocks when you enter any overworld dimension from any nether dimension 7km or more from where you entered.

### Steps/models to reproduce

Create a new overworld and/or nether dimension and use either in the process of getting the "Subspace Bubble" advancement.

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-5 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4797e3a)
You are running the latest version

**Comment by Machine-Maker** [comment]
This is a craftbukkit-introduced inconsistency. I agree that it should be like the other advancements, world-specific instead of for all worlds that might *look* like the other worlds. It looks like upstream also does this with the changed dimension advancement trigger, translating worlds that use the same generation to the the same identifier.
