### ISSUE TITLE
BanList Type Improvements

### ISSUE THREAD

**Issue by Machine-Maker** [PaperSpigot/Paper#8007]
### Is your feature request related to a problem?

The `BanList$Type` enum does not have a generic which makes the get ban list method not good for API.
```java
ProfileBanList banList = this.getServer().getBanList(BanList.Type.PROFILE);
// vs.
BanList<ItemStack> badBanList = this.getServer().getBanList(BanList.Type.PROFILE);
```

### Describe the solution you'd like.

I think `BanList$Type` should be deprecated and replaced with static final instances of something with a generic parameter for the type of the ban list to enforce the correct return value at compile time.
### Describe alternatives you've considered.

N/A

**Comment by Doc94** [comment]
Yeah the ban api is soooo old... for better methods for IP/UUID maybe add interface extended from BanEntry for the specific case like BanProfileEntry and BanIpEntry or this is so breaking api (i prefer make a breaking here because add all in the same interface....)? i make a PR in [upstream](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/pull-requests/750/overview) a few time ago for a JIRA ticket... but only for handle the basic thing about BanList$Type.NAME creating a BanList$Type.PROFILE for the name/uuid things and bad descriptions in docs about the name.

**Comment by codeHusky** [comment]
NMS's GameProfileBanEntry already exposes GameProfiles that could easily be used to improve the API. Definitely a worthy addition IMO if it doesn't end up making it into upstream

**Comment by Doc94** [comment]
> NMS's GameProfileBanEntry already exposes GameProfiles that could easily be used to improve the API. Definitely a worthy addition IMO if it doesn't end up making it into upstream

Yeah... My issue its how handle this... If make extenden entry its to "breaking"

**Comment by Machine-Maker** [comment]
Updated this issue to be specifically about fixing the bad `getBanList` method on Server now that it has a generic return type.
