### ISSUE TITLE
Add ability to strip player signatures from chat packets

### ISSUE THREAD

**Issue by codeHusky** [PaperSpigot/Paper#8043]
### Is your feature request related to a problem?

In 1.19.1, Mojang is adding the ability to ban players from all online servers after reviewing reports of messages reported via in-game tools. This has been seen by many server admins, users, and developers as a bit of an over reach, as well as likely extremely abusable.

### Describe the solution you'd like.

A paper config flag allowing server owners to strip the signature data from chat message packets would prevent users from creating reports (more importantly, abusive reports) against users on their server. Many poorly designed chat plugins will likely already do this, but I can’t see a reason not to add it as a paper option just to solve the problem without the need of an extra plugin/bloat.

### Describe alternatives you've considered.

It’s very possible this is completely out of scope for what the Paper project is intending to do, but I believe this tweak will be something many network operators would like to enable to prevent abuse by their members. Spam reporting staff for messages that, when taken out of context, can appear harmful could result in suspension of their moderation team for no reason.

**Comment by kennytv** [comment]
Aside from the fact that Spigot already completely breaks message signature handling, even if it didn't/doesn't in the future, we will not add such an option. Mojang have already outlined how they are only going to strike down the worst kind of people *noone* should have on their server/things that are outright illegal anyways here https://help.minecraft.net/hc/en-us/articles/7149823936781.

Basically every major social platform you have ever used has some kind of moderation, this was long overdue in Minecraft Java and still is a lot tamer and less intrusive than it is in other places, so disabling this would do nothing but harm your playerbase by making them powerless against proper hate crimes unless they go to *you* specifically, then only being able to take action on *your* server, if at all.

**Comment by NoahvdAa** [comment]
Additionally; this could also quite easily be done by a plugin

**Comment by Korgen1** [comment]
> Mojang have already outlined how they are only going to strike down the worst kind of people _noone_ should have on their server/things that are outright illegal anyways

Yeah well that’s assuming Microsoft stays true to their word (_which it seems like they aren’t already_) and abuse doesn’t run rampant in their system like every other user report system. You really think they are going to be paying people a reasonable wage to read through user reports? I’d bet on them outsourcing to third world countries and paying basically nothing for people to make split second decisions on the future of your ability to play Minecraft. I’ve seen it all the time with platforms like Twitter, YouTube and Roblox. They all suffer from this same problem and I can’t see this ending any different.

> Basically every major social platform you have ever used has some kind of moderation, this was long overdue in Minecraft Java and still is a lot tamer and less intrusive than it is in other places, so disabling this would do nothing but harm your playerbase by making them powerless against proper hate crimes unless they go to _you_ specifically, then only being able to take action on _your_ server, if at all.

Ok but it’s MY server and I should be able to determine what is allowed and what isn’t. Minecraft is different from most other social platforms because it allows us to host our own servers on our own hardware on our own network, but Microsoft is taking away our right to control what happens on our property. Sure if twitter or discord wants to control what is said on their platforms that’s their right because it’s their servers and if this was exclusive to realms it would be ok, but now you have Microsoft moderating our property and it isn’t right.

**Comment by NoahvdAa** [comment]
Once again, these workarounds could also easily be done via a plugin

That aside, this is not really the place to discuss this. People get emails for every message sent on here, so this discussion would generate a lot of spam.

**Comment by ghost** [comment]
Embrace. Extend and extinguish.

**Comment by ElBananaa** [comment]
> > Mojang have already outlined how they are only going to strike down the worst kind of people _noone_ should have on their server/things that are outright illegal anyways
> 
> Yeah well that’s assuming Microsoft stays true to their word (_which it seems like they aren’t already_) and abuse doesn’t run rampant in their system like every other user report system. You really think they are going to be paying people a reasonable wage to read through user reports? I’d bet on them outsourcing to third world countries and paying basically nothing for people to make split second decisions on the future of your ability to play Minecraft. I’ve seen it all the time with platforms like Twitter, YouTube and Roblox. They all suffer from this same problem and I can’t see this ending any different.
> 
> > Basically every major social platform you have ever used has some kind of moderation, this was long overdue in Minecraft Java and still is a lot tamer and less intrusive than it is in other places, so disabling this would do nothing but harm your playerbase by making them powerless against proper hate crimes unless they go to _you_ specifically, then only being able to take action on _your_ server, if at all.
> 
> Ok but it’s MY server and I should be able to determine what is allowed and what isn’t. Minecraft is different from most other social platforms because it allows us to host our own servers on our own hardware on our own network, but Microsoft is taking away our right to control what happens on our property. Sure if twitter or discord wants to control what is said on their platforms that’s their right because it’s their servers and if this was exclusive to realms it would be ok, but now you have Microsoft moderating our property and it isn’t right.

If this system is only used to ban people enforcing **laws** then no, **you shouldn't have your word on what happens, even tho it's on your server**.

Too many people (especially in the minecraft community) are basically spreading hate messages, or are harassing other players, and that's a real issue, not only because a lot of children play this game, but also because too many servers make the choice to ignore these messages.

You can have your own server, hosted on your own hardware, and you can tell users that there's no rules on your server, but it would be a lie.
Imo Mojang shouldn't only punish users in this case, but also the server owners, as they also are responsible for what happens on their servers.

**Comment by Korgen1** [comment]
> If this system is only used to ban people enforcing **laws** then no, **you shouldn't have your word on what happens, even tho it's on your server**.

That is absolutely not true. This is only the case when you agree with the values and laws of your government. What's to stop an oppressive regime from telling Microsoft that all player messages originating from their country needs to be sent to their government. The fact that Minecraft chat messages can be traced back to an account at all is a huge blow to the free internet as this has in the past actually been used to get crucial information into regimes.  

> Too many people (especially in the minecraft community) are basically spreading hate messages, or are harassing other players, and that's a real issue, not only because a lot of children play this game, but also because too many servers make the choice to ignore these messages.

Then don't play those servers?

> You can have your own server, hosted on your own hardware, and you can tell users that there's no rules on your server, but it would be a lie. Imo Mojang shouldn't only punish users in this case, but also the server owners, as they also are responsible for what happens on their servers.

It's true that a server owner is responsible for what happens on their server and servers have been banned from minecraft before. This is an entirely different issue than the content of chat being sent to Microsoft and being identifiable to who sent it.

**Comment by lynxplay** [comment]
I am afraid you did not read noah's comment.
> That aside, this is not really the place to discuss this. People get emails for every message sent on here, so this discussion would generate a lot of spam.

Please do not use github issues for ranting about a system kenny already said we won't actively fight mojang on.

**Comment by Machine-Maker** [comment]
The issue tracker is not the place to discuss this, use the [forums](https://forums.papermc.io) for discussing the chat reporting system.
