### ISSUE TITLE
VehicleDestroyEvent and VehicleDamageEvent dont trigger on vehicles in the void

### ISSUE THREAD

**Issue by daakubotto** [PaperSpigot/Paper#8154]
### Expected behavior

For a vehicle that dies or takes damage in the void to trigger it's VehicleEvent

### Observed/Actual behavior

No events are fired, no EntityDamageEvent, no VehicleDamageEvent, no VehicleDestroyEvent making it impossible to trick vehicles disappearing into the void

### Steps/models to reproduce

1. Listen to the VehicleDamageEvent and VehicleDestroyEvent
2. Push a minecart or boat into the void
3. Observer as neither trigger

### Plugin and Datapack List

Viaversions 3.1.1, other than that clean install

### Paper version

Paper 1.19 build 62

**Comment by Machine-Maker** [comment]
The javadocs for VehicleDestroyEvent say they aren't called when the entity is simply removed. Which is the case in the void.

There is a possible use case for a removal reason, which could then be used with the EntityRemoveFromWorldEvent to catch all cases like this, but I don't think either of those events should be called for removal in the void.

**Comment by lynxplay** [comment]
Closing this as I agree with MM here. Non-LivingEntities are simply removed when going out of the world/into the void.
Hacking the vehicle destroy event into there seems off as the entity isn't destroyed, e.g. nothing drops nor any other destroy logic one would expect is called. The entity is simply removed.

You can use the https://jd.papermc.io/paper/1.19/com/destroystokyo/paper/event/entity/EntityRemoveFromWorldEvent.html

I presume there is a world where more information about the context of an entities removal can be exposed in that event to make stuff like "removed due to void" easier, but this is outside of the scope of this issue and is a feature request.
