### ISSUE TITLE
Adding text to a Map Cursor (via a plugin) causes all map cursors on that map to display a blank text field

### ISSUE THREAD

**Issue by conure512** [PaperSpigot/Paper#8229]
### Expected behavior

MapCursors with set captions display their text beneath them, and cursors without captions have no text and the text field is absent.

### Observed/Actual behavior

I'm writing a plugin that adds captions (using setCaption()) to MapCursors that aren't banners. Whenever I do this in Paper, every cursor on the map, including the player location icon, starts displaying a blank text field beneath it. Removing those specific cursors again by changing the plugin's code causes the issue to go away.

### Steps/models to reproduce

Acquire or create any plugin that allows you to add a caption to a MapCursor. Add a captioned cursor to a map. You'll observe that any additional cursor added to the map, including the one marking the player's location, will now display a text field underneath it containing no text (it'll look like a dark vertical line).

### Plugin and Datapack List

Plugins: Only my own plugin that I'm writing, which applied the captions to the cursors.
Datapacks: Vanilla and the Bukkit default datapack (both unmodified).

### Paper version

This server is running Paper version git-Paper-103 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: c032050)
You are running the latest version

### Other

I've tested this on both Spigot and Paper, using the exact same plugin, world, and map item. The issue is ONLY present in Paper. Additionally, the vanilla-Minecraft method of adding text to maps (naming a banner and then clicking it with the map) doesn't cause the issue to occur.

**Comment by lynxplay** [comment]
Can replicate this. This should be a somewhat easy fix for anyone interested in it.
Generally speaking, the adventure patch https://github.com/PaperMC/Paper/blob/a311dcecb3a7066a56175834a7aac2a2ba65f8bb/patches/server/0008-Adventure.patch#L2541-L2542 switches out ChatMessage.fromStringOrNull which also maps "" to null.
The fact that that decoration even is "" instead of null however is (at least in my opinion) dumb (and also a spigot introduced thing). 
For that, see https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/map/CraftMapRenderer.java#45, which uses `CraftChatMessage.fromComponent` which in turn maps a null component to an empty string for whatever reason.

**Comment by lynxplay** [comment]
Marked this as a good first issue, the fix for this should be really straight forward by just completely removing the legacy usage in the logic found in the CraftMapRenderer 👍 whoever fixes this, this should go into the adventure patch.
