### ISSUE TITLE
@org.bukkit.UndefinedNullability does not show up in javadocs

### ISSUE THREAD

**Issue by lynxplay** [PaperSpigot/Paper#8251]
### Expected behavior

The entire annotation, including its content should be documented on the javadocs to allow developers to see what exactly the contract is.

### Observed/Actual behavior

The annotation is missing from current javadocs.

### Steps/models to reproduce

Go to your local resident paper javadocs and be disappointed.

### Plugin and Datapack List

N/A

### Paper version

bef2c9d005bdd039f188ee53094a928e76bd8e59

### Other

This is an easy fix for anyone willing to PR this 👍 
The https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/annotation/Documented.html annotation is missing from the mentioned @org.bukkit.UndefinedNullability annotation.

This change should live in https://github.com/PaperMC/Paper/blob/master/patches/api/0176-Fix-Spigot-annotation-mistakes.patch

**Comment by Doc94** [comment]
its not better change the annotation for Nullable/NotNull? i mean this annotation is deprecated and dont understand why is used currently...

**Comment by lynxplay** [comment]
It is deprecated because no new method should use this. As stated in the deprecation reason, it is pretty terrible API design to have a method that, for example, is NotNull for players and Nullable for entities.

You cannot replace the annotation on these without either a) using the wrong annotation for a specific case or b) having to change the method itself, leading to a functionality break with spigot.

**Comment by Doc94** [comment]
> It is deprecated because no new method should use this. As stated in the deprecation reason, it is pretty terrible API design to have a method that, for example, is NotNull for players and Nullable for entities.
> 
> You cannot replace the annotation on these without either a) using the wrong annotation for a specific case or b) having to change the method itself, leading to a functionality break with spigot.

hmm, i try to find the currently use.. because in upstream this annotation its used by.

- [org.bukkit.material.Colorable#setColor](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/material/Colorable.html#setColor(org.bukkit.DyeColor)) can be null for shulkers and the rest not, why cannot set a default like in shulkers.. or make all same...
- [org.bukkit.inventory.MapMeta#setMapView](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/MapMeta.html#setMapView(org.bukkit.map.MapView)) not sure here why the annotation... CB allows null and not sure if the maps need this condition
- [org.bukkit.event.server.ServerListPingEvent#setServerIcon](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/server/ServerListPingEvent.html#setServerIcon(org.bukkit.util.CachedServerIcon)) mentioned in docs about cache... 

broke everything and fix this.. but well its more easy add the annotation mentioned for show in docs and let players test and know if use null or not xd

**Comment by lynxplay** [comment]
Well upstream forgot that annotation in a few places, hence why paper has the patch references in the original issue text.
Yes long term this should be fixed by properly refactoring the API and ensuring a proper either nullable or not null return type.
For now, the annotation should however still show up in the documentation.
