### ISSUE TITLE
Implement dev API to serialize specific packets

### ISSUE THREAD

**Issue by PedroMPagani** [PaperSpigot/Paper#8311]
### Is your feature request related to a problem?

It is, currently the PacketEncoder in NMS does not take any advantage at all in reusing bytes on networking, I'm specifically talking about the PacketDataSerializer ByteBuf, some packet writings are very expensive such as entity metadata, if you're sending it for 100 players and have an avg of ~50 ~40 metadata packets(let's say for example for some sort of upgrading holograms line per player), you're basically gonna endup with your netty thread being kind of very busy because of it, which leads to a LOT of delay in clients because of it being busy.

### Describe the solution you'd like.

If having an interface so developers can add a override for encoding the packet, currently if you instance an packet and try to override a method of it, the player will get kicked when the packet is getting encoded in the PacketEncoder class because of onnectionProtocol unknown, so developers cannot override the .a method in packets (NMS obfuscated),

### Describe alternatives you've considered.

What I would've thought about is simply, knowing that the packet won't change its data specially in the metadata packet when getting sent to many players, I could simply copy all the bytes from 1 ByteBuf to the other, without having to completely rewrite and recompress all the data, that would save A LOT of cpu time, and better manage resources on the network too.

### Other

This is obviously not a simple request, considering that most people wouldn't use this because its not something so common to encounter, but this could potentially allow a lot of network optimization in paper in the future.

**Comment by electronicboy** [comment]
This is imho generally a no go

1) writing internal *and especially complex internal* API is generally a no-go, the effort + usecases involved is generally a no go, the nichety of such use-cases often entirely outweighs the hours upon hours of effort even tryna collate an API design for addressing enough use-cases to justify this type of stuff, and that's before you get into the fact that we generally don't write internal API because we don't wanna have to document or maintain or support it

2) Long term, I want to replace a chunk of the logic in the current networking thing, I've not seen packet serialisation itself being much of an issue in the past, but, I don't really wanna write API around stuff we're planning to replace anyways

3) for talking about what you wanna do
a) You'd probably need to replace a good chunk more than just mapping an ID if you wanna skip certain things, other parts of the chain are still going to be trying to do stuff, at the point at which you're tearing the pipeline apart, idk why you wouldn't just replace the encoder

b) while numerous, most of these packets are kinda small, I don't really see a strategy here which actually improves too much; you'd probably need to rely on heap bufs or deal with blocking in order to safely cache such bufs, no idea how this would play like libraries with ProtocolLib, but, that just sounds like a nightmare

**Comment by PedroMPagani** [comment]
I do understand all the points you've made, the main reason of this serialization is due to the Metadata packet of the entity, if sending 100 metadatas a second(with let's say 100 players online) each player would go about having a new PacketDataSerializer for this, which is quite expensive for the netty thread, specially because this is kind of very complex build, every player receives the same packet, but new serialization 100 times, and it's 100 players, so it's 10k serializations of that packet.

Wondering about your 1.3 point, by replacing the encoder you meant changing the source code of the paper directly or I would be able to add a last on that channel being an encoder?

**Comment by Owen1212055** [comment]
I agree, this seems out of the scope of Paper as an API and would expose too much of an internal implementation. I also don't see many cases where 100 players would be in the same place where they would receive each packet (and where the size would really matter that much). 

I will be closing this, however if anyone has something to add to this feel free to comment and this can be reopened. 
Thank you... 😄
