### ISSUE TITLE
BlockExpEvent fires twice for furnaces containing xp

### ISSUE THREAD

**Issue by Xeonmeister** [PaperSpigot/Paper#8356]
### Expected behavior

When i mine a furnace block which has stored exp in it the event should fire once with the furnace block and the correct xp amount.

### Observed/Actual behavior

The event fires twice:
1. The block is 'furnace' and the xp is 0
2. 2. the block is 'air' and the xp is the correct value

### Steps/models to reproduce

- Set up a BlockExpEvent listener which prints out the block and exp values.
- Place a furnace and wait for it to smelt for eg 1 cactus (1 cactus adds 1 exp to the furnace).
- Mine the furnace block.

### Plugin and Datapack List

No datapacks and only the debug plugin with the BlockExpEvent listener.

### Paper version

[20:20:44 INFO]: This server is running Paper version git-Paper-139 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 36a5f15)
You are running the latest version

### Other

![event](https://user-images.githubusercontent.com/11841097/189418381-39147c04-cae0-4ee3-8dde-dce683485f1f.png)
![console](https://user-images.githubusercontent.com/11841097/189418408-4dddd31d-a0de-4ef9-93d3-d6a8ea54683d.png)

**Comment by Machine-Maker** [comment]
This is works as intended. One of those events is actually a BlockBreakEvent. You can then easily filter out any duplicate by checking if one of the events is an instance of BlockBreakEvent.

This is due to how furnaces handle XP. All BlockBreakEvents for all blocks are also BlockExpEvents (for blocks like red stone ore which drop EXP), but furnace blocks have special logic to also dropped the xp for the items smelted, and that is handled separately.
