### ISSUE TITLE
No way to determine if mud changed to clay

### ISSUE THREAD

**Issue by PapiCapi** [PaperSpigot/Paper#8366]
### Expected behavior

It would be useful to have an event where you could get the initial block ( mud ) and the final block ( clay ).

### Observed/Actual behavior

I only found the BlockPhysicsEvent triggered but i didn't find any way to get the initial block ( mud ).

### Steps/models to reproduce

Create the appropriate structure to create some clay from mud 

### Plugin and Datapack List

/

### Paper version

Paper version git-Paper-153 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 63cb747)

### Other

Here is the structure that changes the mud to clay if you wait a bit ( or just increase the randomTickSpeed )
![Screenshot_1](https://user-images.githubusercontent.com/49530141/190911695-cfbebc4c-a3b6-47ce-a5b9-0023b53c872b.png)

**Comment by lynxplay** [comment]
Generally a rather easy addition of an event call (`net/minecraft/world/level/block/PointedDripstoneBlock.java:L216` simply changes the block without publishing an event first).

The only thing that has to be determined here is what event should be called.
I'd personally would like to nominate https://jd.papermc.io/paper/1.19/org/bukkit/event/block/BlockFormEvent.html as it is also called for concrete powder's interaction with water.

Due to this question, community input here in regards to what event makes the most sense here (of if we need a new event) would be great!

**Comment by Machine-Maker** [comment]
What event is called when stone is changed to moss via bonemealing moss? If there is an event there, I think it should be the same event.

**Comment by Owen1212055** [comment]
I'm not sure if an event is called there? It looks like it just creates a feature there, which I assume wouldn't really call any replacement block events.
![image](https://user-images.githubusercontent.com/23108066/190913808-21feaeff-2439-4991-83d2-eb02f8376b9a.png)
