### ISSUE TITLE
PluginMessageEvent, A good solution for not killing databases or overcomplexing something that should be simple

### ISSUE THREAD

**Issue by PedroMPagani** [PaperSpigot/Paper#8406]
### Is your feature request related to a problem?

Yes it is, data management, currently in all spigot-servers we know how a proxy works, and the main issue with that is because most developers have the common, saving data only on PlayerQuitEvent, right? yeah, what happens is:

The order of the events when using a proxy is actually very different, since the AsyncPlayerPreLoginEvent is actually called before the PlayerQuitEvent, which could cause many issues including data-loss, specially if the developer is taking advantage  and loading data on the threads that handle the (AsyncPlayerPreLoginEvent), and the only solution would be to kind of "over-kill" the processing by saving to the database any changes made, so that there wouldn't be any data loss related to concurrency and timing issues.+

### Describe the solution you'd like.

My solution is basically developers would have this PluginMessageEvent, this event would be run async, and only after processed the packet would actually be sent (causing the player to send whatever he is trying to send), this way developers would be able to take advantage of this API and save data correctly without having to "spam the database" many times just to make sure nothing bad happens to the player data databases-side.

The event would contain the message encoded in bytes, which would mainly make possible for developers to read the message and see if this could be a connection message (since we don't really need paper to always read it and confirm its a TryConnectEvent with the proxy i think it would be more of- let the Developers use it, if they want to).

### Describe alternatives you've considered.

I've actually just listened to everything that sends the Player to another server and i handle the data there, even tho its a messy solution and not wise, since i had to add a common api and all plugins that use "connect" call it before

**Comment by electronicboy** [comment]
a plugin message event won't change anything much here, you'd need a handshake process authoritative by the proxies in order to actually do too much; That idea was discussed elsewhere but generally "nope'd"

**Comment by PedroMPagani** [comment]
@electronicboy in that case, do you have any alternative solution for this? maybe you have already deal with this and could provide some sort of accurate model for the data handling that could potentially help even future Devs visiting this suggestion

**Comment by electronicboy** [comment]
during login, the server and the proxy would talk to one another, so that the proxy registers the relevant messaging channel and the server lets the proxy know "hey, I support being told about a server switch incoming"

if that handshake occurs, when switching servers, you send a message to the server to say that the player is going to do a server transition, you would probably have to have some way to ensure that the server initiates the process of firing an event, after which the event is fired, you tell the proxy that the process was completed; Many dozen caveats still, however; how do you handle server transfer fails, i.e. letting the server know that the player is still gonna be there, especially if you wanted to shove them into some limbo'd state on the origin server when doing the jump
