### ISSUE TITLE
Custom world teleport rollback bug

### ISSUE THREAD

**Issue by LeeTheTech** [PaperSpigot/Paper#8435]
### Expected behavior

That the chunks don't rollback from the teleported location when a user teleports to a custom world from a normal world.

### Observed/Actual behavior

When a user teleports to a custom world, made with WorldCreator, it'll rollback the chunks they teleported from if they allow them to unload after they teleported.

### Steps/models to reproduce

1. Place blocks in normal world
2. Teleport to a custom world made with WorldCreator
3. Wait for the chunks to unload from the location you teleported from in the normal world
4. Teleport back to normal world

### Plugin and Datapack List

CoreProtect, GoldmanChunks, GoldmanCore, GoldmanEnchants, GoldmanEssentials, GoldmanHats, GoldmanLocker, GoldmanMysteryBox, GoldmanNPC, GoldmanPets, GoldmanShops, GoldmanSkins, GoldmanTrails, Pl3xMap, ProtocolLib, Themis

### Paper version

paper-194 - 1.19.2

### Other

I made a video of this test: https://youtu.be/P9s4EFogS2I

Might want to skip to the end after you see me place the blocks and teleport to the custom world.

**Comment by Crnojevic** [comment]
I can confirm experiencing the same behaviour on a server since at least version 1.18, which is when we first noticed chunks reverting, never made an issue of my own because I hadn't figured out what was causing it. Wouldn't be surprised if it had actually been going on for longer and nobody had reported it.

You can see in this screenshot where the roof of a house being built disappeared in one single chunk that got reverted while the surrounding chunks are fine.

![IMG_20221006_012725_799](https://user-images.githubusercontent.com/107649181/194187425-5775b413-4729-4460-ae29-778bfc12ccaf.jpg)

A chunk of melons reappeared after being harvested, the other chunks are still gone - you can see dirt where the grass hasn't yet regrown on the other chunks that contained melons.

![IMG_20221006_013004_664](https://user-images.githubusercontent.com/107649181/194187587-74fd3720-dfc8-448e-a3d1-f97c6ff692fe.jpg)

# Plugins
AntiWorldFly, BackOnDeath*, CommandBook, CoreProtect, DiscordSRV, EntityDetection, ExodusHomes, GSit, HomeInviteExodus, InvisibleWorkbench*, KeepChunks, LockettePro, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, NoChatReports, NoSpawnerChange, PermissionsBukkit*, PerWorldInventory, Pl3xMap, Pl3xMap-VanishNoPacket, Pl3xmap-WorldGuard, PlayerDeathLocations*, ProtocolLib, SexyMotd*, spark, VanishNoPacket, Vault, WorldBorder*, WorldEdit, WorldGuard

**Comment by Crnojevic** [comment]
@SirLeezus can you try removing Pl3xMap and see if you still have the same problem?

**Comment by LeeTheTech** [comment]
> @SirLeezus can you try removing Pl3xMap and see if you still have the same problem?

Yup, I'll do another test later tonight.

**Comment by lynxplay** [comment]
I'll be closing this as generally, leafs commit (https://github.com/PaperMC/Paper/commit/fc5ae5be8255b9d1c03a551d656543a85b091f64) fixed these issues.

If you can still replicate it without plugins on latest, please comment on the issue and I can reopen it :)
