### ISSUE TITLE
Replace usercache.json with Redis

### ISSUE THREAD

**Issue by Euphillya** [PaperSpigot/Paper#8437]
### Is your feature request related to a problem?

Currently, the usercache.json can by default go up to about 100kb, so has a limited number of players in the cache. This cache can quickly become saturated with a lot of players and having a json file for the cache that exceeds a megabyte can't necessarily be beneficial in the long run. Having the ability to put it in the Redis will not only be beneficial especially for using the Bukkit#getOfflinePlayer.

Thank you for reading this request.

### Describe the solution you'd like.

Add support Redis in paper-global.yml.

### Describe alternatives you've considered.

Or add an API that would allow us to do our own integration for Redis (or MariaDB...).

**Comment by electronicboy** [comment]
Theres pretty much 0 merit for us adding redis here, such a thing would just get into the realms of too much of an opinionated environment, and bundling libraries like the redis connector or whatever it was is just a joyous PITA.

I could see API for this, maybe; but it gets into a weird area around how much impl detail you expose, given that system is what ends up speaking to mojang for many requests...

**Comment by Owen1212055** [comment]
Generally, I see no point in going this far as well.
If you use PlayerProfile#complete(), the resolved game profile will be added to the cache. So you could possibly populate the cache just by completing game profiles on a separate thread.

If you really are connecting your network this much, I'd recommend just using NMS to do this for you because I feel like this is way too implementation specific. as

Additionally, you can use the PreLookupProfileEvent to manually set the player/uuid, working around the built-in cache and it will avoid the network call. 
![image](https://user-images.githubusercontent.com/23108066/198141942-b66153b8-162b-4da0-8c9e-acf1a9a1e7ca.png)
