### ISSUE TITLE
Tameable entity get teleportet to player after re-connect

### ISSUE THREAD

**Issue by morfeyc** [PaperSpigot/Paper#8462]
### Expected behavior

Tameable entity have to remain leashed at their positions

### Observed/Actual behavior

Tameable entity teleports to player and unleashes

### Steps/models to reproduce

https://youtu.be/8fpqHAmN1uU

### Plugin and Datapack List

no plugins
standard datapack: [vanila (build-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-201 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 57555b8)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads

### Other

maybe https://bugs.mojang.com/browse/MC-173303

**Comment by morfeyc** [comment]
If anyone is as fed up with this bug as I am, I made a bukkit-plugin to fix it: [link to github repo](https://github.com/morfeyc/LeashedCatTeleportFix)

**Comment by Owen1212055** [comment]
I can reproduce this as of 1.19.2, including on Vanilla.

Generally, this seems like a very low-priority issue, if anyone wants to give it a shot at fixing this however feel free.

**Comment by Thedysons** [comment]
Despite trying multiple builds, including the one where the issue was initially reported as well as switching to a vanilla server and client I wasn't able to recreate the issue. Its implied that I'm doing something incorrectly because even the bug report states its unresolved, but I'm not sure what I'm missing, I followed the steps taken in the video and tried multiple different distances without any results.

**Comment by Owen1212055** [comment]
Try following the mojang bug report, it seemed to have been reproduced 4 days ago.

**Comment by Gameoholic** [comment]
I too couldn't reproduce this on the latest Paper version
