### ISSUE TITLE
PlayerPortalEvent will not be trigger when a player jump into the end-portal from the_end.

### ISSUE THREAD

**Issue by sakurawald** [PaperSpigot/Paper#8469]
### Expected behavior

PlayerPortalEvent will SHOULD BE TRIGGERED when a player jump into the end-portal from the_end.

### Observed/Actual behavior

PlayerPortalEvent will NOT BE TRIGGERED when a player jump into the end-portal from the_end.
However, then a player jump from overworld into the end-portal, and teleport to the_end, PlayerPortalEvent will be triggered correctly.
And besides, EntityPortalEvent will be triggered BOTH correctly: entities from overworld into the_end, entities from the_end into overworld

### Steps/models to reproduce

SEE ABOVE.

### Plugin and Datapack List

Plugins (5): CMI, CMILib, LuckPerms, PlaceholderAPI, spark
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-210 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 0bdf997)
You are running the latest version

### Other

NONE.

**Comment by electronicboy** [comment]
This is 100% expected behavior due to the peculiarities of this portal. The portal event expects a "to" location, and when using that portal, there is no target location, the player is essentially shoved into a weird limbo state on the server for the credits screen, even if you've not seen the credits, you'll still enter this weird state before what I assume is the client tells you otherwise

EntityPortalEnterEvent is the best event you're gonna see here
