### ISSUE TITLE
Using the portal causes errors and at worst crashes

### ISSUE THREAD

**Issue by Torxscrews** [PaperSpigot/Paper#8497]
### Expected behavior

No errors.

### Observed/Actual behavior

All players are disconnected at timeout or the server crashes.

### Steps/models to reproduce

Player uses the portal.
Prone to happen to players with geyser connection
It doesn't always happen.But it does happen with frequency.

### Plugin and Datapack List

Plugins (14): AFKPlus, AutoSaveWorld*, CoreProtect, floodgate, Geyser-Spigot, GSit, LiveKit, LuckPerms,
 LunaChat*, LWC, MiniMOTD, PlugMan, spark, Timber*

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Paper version

 git-Paper-215 (MC: 1.19.2)

**Comment by Owen1212055** [comment]
> or the server crashes.

Are you able to see how the server crashes? Without logs it's very hard to tell what is happening here.

**Comment by Torxscrews** [comment]
@Owen1212055 
https://mclo.gs/A2PDEsD

**Comment by jonathanebl** [comment]
Im not completely sure but it looks more like the issue is one of your plugins or your server couldn’t handle as much and just crashed you could first try increasing the timeout time in spigot.yml that would replace the crash with large lag spikes if the performance is the issue else i would try to remove the plugins and see if it works

**Comment by Torxscrews** [comment]
What to do when all players are disconnected due to timeout?

**Comment by jonathanebl** [comment]
What have you changed by now and Is the server still crashing or can you reconnect

**Comment by Torxscrews** [comment]
Nothing has been changed. But the problem doesn't seem to have been solved. Need to give it a little more time to monitor its behavior.

**Comment by electronicboy** [comment]
I mean, it's hard to say as we only get so much info

he two general theories towards this type of stuff is either overloaded hardware, or the load request got lost

I'm not familiar with the new chunk system to know if the latter is possible, doesn't look like it, so, more than likely not that

The only thing I can see that stands out is that there is a singular IO thread that is currently in the process of doing a write; The fact that a save-all was apparently just run is suspicious AF, overloaded worker? I would assume that it would however jump to the blocking POI task after a write task was finished, rather than just being stalled out waiting for the rest of the writes, I'd need to find time to run over the logic

**Comment by Torxscrews** [comment]
This issue is difficult for me.
When I asked the question on the Discord help channel, the answer was that it might be a portal issue, but the actual cause of the problem is not clear.

**Comment by electronicboy** [comment]
Actually, just thinking, I'd imagine that the region file stuff would wait for all write tasks to finish before it tries to load, otherwise that would introduce many issues, so this doesn't look like a bug, this just looks like a machine struggling to deal with all of the file writes

**Comment by Torxscrews** [comment]
For now,I will try to move the server storage to SSD.

**Comment by Torxscrews** [comment]
I close this issue as the problem no longer occurs for now.
