### ISSUE TITLE
URL for the newest Version

### ISSUE THREAD

**Issue by c0ntxt** [PaperSpigot/Paper#8516]
### Is your feature request related to a problem?

It's kinda annoying to update every server by hand if you have multiple servers.

### Describe the solution you'd like.

A URL that always downloads the newest version would be very helpful. Everyone is able to create a script for their servers so it can replace the old .jar with the new one without having to do it by hand. 

### Describe alternatives you've considered.

Doing it by hand but that's really time consuming

**Comment by jpenilla** [comment]
This is missing intentionally https://github.com/PaperMC/bibliothek/issues/74

**Comment by lynxplay** [comment]
This has been suggested numerous times, however an endpoint to download the latest version of paper is simply not implemented by design due to:

1. We do not recommend auto updating whatsoever. As a rolling release, you should be testing your server updates in a test environment carefully before pulling in new builds into production.
2. As you already mentioned, this is possible with any 4 to 5 lines of bash script, from which there are a lot of pre-written examples in the discord or on github.
3. etc. etc.
