### ISSUE TITLE
Item Contains Enchant

### ISSUE THREAD

**Issue by dbteku** [PaperSpigot/Paper#8520]
### Expected behavior

```java 
boolean contains = event.getItem().containsEnchantment(new WireToolEnchant());
```

I expect that to return true if the enchant exists. This was working in paper 1.18.x

Now I have to do something like this
```java
boolean contains = event.getItem().getEnchantments().getOrDefault(new WireToolEnchant(), 0) > 0;
```

### Observed/Actual behavior

Always returns false.

### Steps/models to reproduce

1. Create a custom enchantment and recipe and add it to an item (I did a stick)
2. Hook to the PlayerInteractEvent

On the PlayerInteractEvent check if the item in your hand contains the enchant.

### Plugin and Datapack List

ColoredSigns, Essentials, Plugman, Vault, CustomPlugin(Mine)

### Paper version

Paper version git-Paper-245 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b743144)

**Comment by electronicboy** [comment]
Creating custom enchantments like that has always had inconsistencies within the API, and 0 promise is made that such behavior will ever work. This is likely due to some recent changes to some older fix.

Server needs to be able to lookup the actual enchantment, and thus, needs to run through this logic:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1228900/198844066-05e63480-f41c-41fa-bc4f-564f18fecd5f.png">
