### ISSUE TITLE
Can't recognize if in PlayerDeathEvent death message was cancelled

### ISSUE THREAD

**Issue by EpicPlayerA10** [PaperSpigot/Paper#8654]
### Expected behavior

`PlayerDeathEvent#getDeathMessage` should return null.

### Observed/Actual behavior

When you call `PlayerDeathEvent.setDeathMessage(null)` and call `PlayerDeathEvent#getDeathMessage` the return value will be empty string instead of null. This bug makes that you can't recognize if server shouldn't show death message or if it should show empty message.

### Steps/models to reproduce

1. Call `PlayerDeathEvent.setDeathMessage(null)`
2. Call `PlayerDeathEvent#getDeathMessage` and see the return value.

### Plugin and Datapack List

Works with only one plugin: yours, that handles PlayerDeathEvent

### Paper version

This server is running Paper version git-Paper-323 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: d2cb347)
You are running the latest version

**Comment by lynxplay** [comment]
Accepted. While `deathMessage(Component)` allows one to set the adventure component to null, `setDeathMessage(String)` defaults to `Component.empty()` if passed null, leading to an empty string being returned.

I am unsure as to why this was implemented the way it is.
The caller of the event even has a specific check against `Component.empty()` for the return type.
If anyone has some input/memories why this was implemented the way it is, that would be great.
Specifically because the adventure methods already allow you to set things to null and there are checks in place for such a null case.
