### ISSUE TITLE
/locate structure stronghold command expire and unable to use the eye of ender on 1.19.3

### ISSUE THREAD

**Issue by Moranyixiao** [PaperSpigot/Paper#8692]
### Expected behavior

Able to locate 1.19.2's stronghold by command or the eye of ender on 1.19.3 paper client

### Observed/Actual behavior

unable to locate the stronghold by command /locate structure stronghold 
unable to right click use the eye of ender

### Steps/models to reproduce

unable to locate the stronghold by command /locate structure stronghold 
unable to right click use the eye of ender

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/26624650/208228795-43117bc6-6b90-4066-9ca3-3bff724fda1a.png)

### Paper version

Current: git-Purpur-1871 (MC: 1.19.3)*
Previous: git-Purpur-1870 (MC: 1.19.3)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

**Comment by electronicboy** [comment]
1) stucture stuff, especially across versions, is generally unstable; you'd need to validate against vanilla
2) We don't accept reports from software that isn't ours

**Comment by alfredcort** [comment]
I'm also having this issue!

**Comment by alfredcort** [comment]
I can confirm that I'm having this same issue, using Purpur build #1858.

**Comment by alfredcort** [comment]
Did anybody find a fix to this?

**Comment by Machine-Maker** [comment]
> Did anybody find a fix to this?

This is an intentional 1.19.3 change by mojang.

**Comment by alfredcort** [comment]
I understand this, however ender eyes are completely unusable on my server now. There must be some sort of method to allow all old strongholds to still be recognised, my world has been preloaded so no new ones will spawn.> by

**Comment by Machine-Maker** [comment]
Then what you want to do is generate the same world on 1.19.2, use a program to find all stronghold locations within your pre-generated area, then have a plugin which overwrites eyes of ender to point to the nearest location in that set of locations on your 1.19.3 server. But this can be fixed with a plugin, which is why paper won't. Also, if Paper would even think about trying to fix this, we would have to include all of the old structure generation logic from 1.19.2 which we aren't gonna do. Mojang made the change intentionally, and even mentioned it specifically in the patch notes. But there is a workaround, it just requires more effort for server owners.

**Comment by StKillReal** [comment]
> Plugin that help solve this issue: https://www.spigotmc.org/resources/ender-eye-target-changer.82263/

It works when I just put the plugin into plugins folder, or I need to change/add something in config.yml?
