### ISSUE TITLE
Re-adding to the whitelist with a login in a different case(upper/lower)

### ISSUE THREAD

**Issue by liponex** [PaperSpigot/Paper#8809]
### Expected behavior

While server is in offline mode, adding player to whitelist with wrong login upper/lowercase, then removing it and adding with right case, it must add it with right case.

### Observed/Actual behavior

It adds player with the wrong login case.

### Steps/models to reproduce

1. Set server to offline mode
2. Add player with wrong nickname case to whitelist
3. Remove it
4. Add with right case
5. It will add with wrong case

### Plugin and Datapack List

N/A

### Paper version

1.19.3 380, [0ed4b91](https://github.com/PaperMC/Paper/commit/0ed4b9148b72a7fb702333cf1221be6aeecff7ca)

### Other

It also behaves as this in previous versions/

**Comment by liponex** [comment]
As temporary solution for me were to disable whitelist, then player must join, then you add it to whitelist and turn whitelist on

**Comment by NoahvdAa** [comment]
Sounds like this is working as intended. Since there is no communication with Mojang servers in offline mode, there is no correct or incorrect capitalization of a name. UUIDs are generated based on the username in a case-sensitive way.
Additionally, we don't provide support for issues caused by offline mode (like this one).
