### ISSUE TITLE
Force opening a enchanting table inventory not working

### ISSUE THREAD

**Issue by BlockyTheDev** [PaperSpigot/Paper#8818]
### Expected behavior

The Enchanting table should open with the force parameter like the workbench and similar blocks through the direct method instead of the need to use following way at the enchanting table:
```java
player.openInventory(Bukkit.createInventory(null, InventoryType.ENCHANTING));
```

### Observed/Actual behavior

Inventory only opening, when player is standing on an enchanting table.

### Steps/models to reproduce

1. Create a command (or something similar), which is executing following code (Force set to true):
 ```java
player.openEnchanting(null, true);
 ```
2. Execute the command (...)

### Plugin and Datapack List

Plugins (2): LuckPerms, Enchanting-Inventory

### Paper version

[00:43:45 INFO]: This server is running Paper version git-Paper-384 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 18fabc0)
You are running the latest version
Previous version: git-Paper-381 (MC: 1.19.3)

**Comment by lynxplay** [comment]
Upstream is already tracking this issue in https://hub.spigotmc.org/jira/browse/SPIGOT-7029.

The method is barely useful and currently breaks because the logic expects an enchantment tile entity to be there in order to read its display name for the inventory. As that is not the case, the method breaks. Fixing that is bleh as we'd have to either copy the enchantment table creation logic into the craft layer or introduce a bypass to the existing NMS methods.

I'll be marking this as low priority (considering just deprecating that method) concerning that there is a workaround available that uses the proper custom inventory (that you are trying to create) and hence does not rely on forcing a non-existent block entity to open an inventory.

Opinion on this from the team (or other aspiring developers) would be welcome in regards to the decision between:
1. Fixing this via one of the previously described workarounds
2. Deprecating that method for removal
