### ISSUE TITLE
Server Crash when locating structures in custom World

### ISSUE THREAD

**Issue by justin0-0** [PaperSpigot/Paper#8835]
### Expected behavior

I expect to get a Message that no Structure could be located nearby like in the Overworld

<img width="464" alt="image" src="https://user-images.githubusercontent.com/61631935/217824730-448480f6-30d7-4979-91cb-93a25d856363.png">

### Observed/Actual behavior

The Server crashes

### Steps/models to reproduce

Make a Plugin with a ChunkGenerator with only the Method generateNoise()... then generate the world with the Environment Normal and run the command /locate structure minecraft:village_plains or any other structure that spawns in the overworld.

### Plugin and Datapack List

<img width="462" alt="image" src="https://user-images.githubusercontent.com/61631935/217825404-22b6cd7a-263b-4a37-847b-57b35caecf82.png">

### Paper version

<img width="375" alt="image" src="https://user-images.githubusercontent.com/61631935/217825447-5edb3b4c-6277-4e63-84a5-e2fe2184745a.png">

### Other

Thats the Log of the Server Crash and the Code of my Plugin
[2023-02-09-16.log](https://github.com/PaperMC/Paper/files/10697603/2023-02-09-16.log)

The Code from the ChunkGenerator
https://pastebin.com/a9HRGwbA

The Code in my Main Class
https://pastebin.com/bDRkgRML

**Comment by Machine-Maker** [comment]
> --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-388 (MC: 1.19.3) ---

See that line in the log? It's not a crash. The server just couldn't find the structure that you specified. A similar issue happens in vanilla with treasure maps when it tries to find a buried treasure location and can't within a time limit.

Your chunk generator doesn't generate any structures because the method in ChunkGenerator `shouldGenerateStructures()` returns false unless you override it. A better place for questions about this would be the discord or forums.
