### ISSUE TITLE
 /kill on EnderDragon doesnt fire EntityDeathEvent

### ISSUE THREAD

**Issue by cunhar** [PaperSpigot/Paper#8836]
### Expected behavior

when i /kill an entity EntityDeathEvent should fire

### Observed/Actual behavior

/killed an ender dragon and the event never fired

### Steps/models to reproduce

summon enderdragon

/kill ender dragon

nottice that EntityDeathEvent does not fire

### Plugin and Datapack List

none besides the one im developing 

### Paper version

 paper-1.19.3-388

**Comment by lynxplay** [comment]
Replicable, however it remains to be determined if this works as intended or not.
Living entities rely on a damage of Float.MAX_VALUE whereas the enderdragon simply removes itself from the world on
Entity#kill.

I am conflicted here, mostly because I don't see the usecase here for a command but also because it would put an event in a part of the logic that might be called from really a lot of weird places. Other opinions here would be appreciated.
For reference, see the difference between

EnderDragon#kill and LivingEntity#kill

**Comment by cunhar** [comment]
@kennytv the event still doesnt fire when the /kill command is run

**Comment by kennytv** [comment]
It definitely is. Make sure you're up to date and that your listener is registered.
