### ISSUE TITLE
Removing RunningOnDifferentThreadException

### ISSUE THREAD

**Issue by Mercenarioo** [PaperSpigot/Paper#8837]
### Timings or Profile link

.

### Description of issue

Is RunningOnDifferentThreadException needed? Doesn't throwing the exception on every incoming packet cause performance problems? Thanks for answer!

### Plugin and Datapack List

.

### Server config files

.

### Paper version

master

**Comment by electronicboy** [comment]
1) throwing exceptions is generally not expensive enough to care
2) That's generally the control flow that mojang for some ungodly reason used, and the implications of it are not worth the debt to change that behavior

**Comment by Mercenarioo** [comment]
On some spark reports I saw that exceptions can cause lag, depends of the type. I doubt that in Velocity there is the same exception system, maybe it's a good idea to improve that?

**Comment by electronicboy** [comment]
The exception is cached, meaning that the expensive parts of the exception are not an issue, I'm not exactly sure how spark would record the cost of a thrown exception in any form or reliable manner; but, this is generally not an issue, and fixing this would generally incur a sizable amount of changes of which maintaining those changes would be far more of a headache than it's worth; Throwing a cached exception is generally not all that expensive, and definitely not expensive enough to have to completely butcher the entire network handling logic

**Comment by Mercenarioo** [comment]
I think there's a reason this solution is not used in any other project, also we saw many examples in Paper that you shouldn't totally trust Mojang's code.

**Comment by electronicboy** [comment]
Because using exceptions for control flow is generally stupid, and the implementation decision to use an exception for this is generally stupid and makes fixing it a headache as now you've got to deal with the technical issue of deciding how to properly refactor the codebase to change the control flow to avoid that

This isn't anything to do with "trusting mojangs code", this is a "throwing a cached exception is not expensive enough to justify completely changing how the packet handler works here", if this was something that was stupidly expensive and on the main thread, sure; But this is in the netty event loop, where it's not like there is much care in regards to saving CPU cycles, especially for the amount of technical work that would otherwise be required

**Comment by Mercenarioo** [comment]
Sure, I get it, I think it was worth mentioning, maybe you could add this in the future. Thanks for fast answers. :)
