### ISSUE TITLE
PlayerReadyArrowEvent does not fire when players hold the arrow in their offhand

### ISSUE THREAD

**Issue by Thatsmusic99** [PaperSpigot/Paper#8841]
### Expected behavior

That the event PlayerReadyArrowEvent fires when the player holds an arrow in their offhand, which is prioritised over other arrows in the inventory.

### Observed/Actual behavior

The event, well, does not fire.

### Steps/models to reproduce

1. Have a plugin listening to the event.
2. Hold an arrow in the hotbar, confirm that it fires.
3. Hold an arrow in your offhand, confirm that it doesn't fire despite the arrow being used when firing.

### Plugin and Datapack List

All plugins for a test server and confirmed elsewhere but just to confirm:
- AdvancedTeleport
- ATHENA
- ClearLag
- CratesPlus
- HeadsPlus
- LuckPerms
- Multiverse-Core
- PlaceholderAPI
- Spoofer
- Vault
- ViaVersion

Datapacks:
- vanilla
- file/bukkit

### Paper version

This server is running Paper version git-Paper-396 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: bd77b78)
You are running the latest version
Previous version: git-Paper-379 (MC: 1.19.3)

**Comment by Machine-Maker** [comment]
This looks legit. The logic for selecting an arrow in a held slot is separate from searching the inventory. This is because certain projectile weapon items support different ammunition if its held in a hand vs sitting in a random inventory slot. A solution would be to add a new firing of the event where that logic happens in ProjectileWeaponItem#getHeldProjectile because you need to test both the off and main hand held items.

**Comment by Thatsmusic99** [comment]
Sounds good, I'm currently looking into it myself since I have a time-sensitive project that is quite badly disrupted by this, rip

If someone doesn't beat me to it I'll see if I can get it fixed or PRed? I haven't done such a thing to Paper before and thought it'd be a good opportunity to at least do so. :P
