### ISSUE TITLE
NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because "this.entity.H" is null

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#8983]
### Expected behavior

No exception.

### Observed/Actual behavior

Exception is thrown.

### Steps/models to reproduce

Just in case, I'll report it here too. Initial issue, reproduction steps, stacktrace etc.: https://github.com/EngineHub/WorldGuard/issues/1987

### Plugin and Datapack List

```
[15:16:34] Bukkit Plugins:
[15:16:34]  - Chunky, ChunkyBorder, CoreProtect, Essentials, EssentialsGeoIP, EssentialsSpawn, LuckPerms, MobArena, MobArena-AR, NoCheatPlus, OpenInv, Orebfuscator, ProtocolLib, Vault, WorldEdit, WorldGuard
```

### Paper version

```
This server is running Paper version git-Paper-"fe88107" (MC: 1.19.4, Git: fe88107 on dev/1.19.4)
```

**Comment by Jikoo** [comment]
Caused by https://github.com/PaperMC/Paper/blob/85a67dadf28ff329cc01429de84b8b62262435e6/patches/server/0384-Move-player-to-spawn-point-if-spawn-in-unloaded-worl.patch
I know I'm biased because this patch is causing me grief, but isn't a better solution to just move the player immediately to the spawn point?

**Comment by jpenilla** [comment]
No, it's not a better solution, it would create more diff for no benefit to Paper. Creating and loading ServerPlayers/implementing Bukkit Player isn't something that's supported, you probably need to manually set the world again after loading.

**Comment by Jikoo** [comment]
Fair. Annoying to have to work around changes for Paper, but I guess that's where Paper plugins will come in when that stabilizes.

**Comment by jpenilla** [comment]
Needing to account for internals changes is nothing new, for example, starlight and the chunk system rewrite. But yes, Paper plugins will make it easier to load different code on Paper while keeping spigot support for that 1% of users

**Comment by Jikoo** [comment]
Paper's changes have forced me through hoops while trying to use exclusively Bukkit API features as well (namely tile entity drops - the patch for something related to beehives that I no longer remember the details of also made it so that block drops include inventory contents), so I guess I was a little pre-salted here. "Paper back at it again" when it's just a reasonable thing to do.
Appreciate you guys keeping servers performant 👍
