### ISSUE TITLE
Used YAML version seems to contain a high-severity exploit

### ISSUE THREAD

**Issue by TheFruxz** [PaperSpigot/Paper#9016]
### Expected behavior

A safe use of dependencies and not getting notified due to possible threats

### Observed/Actual behavior

IntelliJ is notifying me, due to 2 possible issues

![SCR-20230320-nzp](https://user-images.githubusercontent.com/28064149/226402577-4c98d4d0-c2ee-48ee-9fc8-73d3329b03b5.png)

One issue even published last year with high risk: https://devhub.checkmarx.com/cve-details/CVE-2022-1471/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea&utm_term=maven

### Steps/models to reproduce

- Add the dependency to your gradle project

### Plugin and Datapack List

/

### Paper version

/

**Comment by lynxplay** [comment]
Both of these are respective issues for untrusted data, which is not the case for configuration files provided by the server.
1.33 already has options to prevent CVE-2022-1471.
CVE-2022-41854 should have been fixed in 1.32, so I am unsure why it still shows up.

In general, bumping snakeyml to 2.0 (which is the version fixing the CVE-2022-1471 contains breaking changes that would break plugins.
Spigot stated in their update statement for 1.19.4 that they are already planning an upgrade in the next release (1.20 I presume?).
Until then, YamlConfiguration already uses its own SafeConstructor subtype compared to the vulnerable Constructor type.

Plugins that actively use snakeyaml beyond the spigot provided wrappers should implement their own measures here, they'd have to anyway if bumped to 2.0. Until fixed, I guess we *can* leave this open as a tracking issue but I don't think it is required for us to bump to a breaking version of snakeyaml for something that should not really be happening unless a plugin is actively using snakeyml to parse untrusted (from the perspective of the server) yaml data.

**Comment by lynxplay** [comment]
After some further discussion, we are aware enough of this, especially in regards to the upstream announcement of a bump in the next release, that a tracking issue is not needed.

I hope you can understand my points listed above as to why 1.33 should not pose a significant threat to servers outside of the previously defined exception.
