### ISSUE TITLE
setPlayerProfile makes player go invisible to others

### ISSUE THREAD

**Issue by alex6777** [PaperSpigot/Paper#9061]
### Expected behavior

Player not be invisible after running setPlayerProfile 

### Observed/Actual behavior

Player goes invisible after running setPlayerProfile with this error in the other player's client logs

`Server attempted to add player prior to sending player info (Player id f3c4dfb9-1c7b-40ac-81fd-462538538523)`

### Steps/models to reproduce

PlayerProfile profile = Bukkit.createProfile("Simon");
profile.complete();
player.setPlayerProfile(profile);

Other clients that were online won't be able to see player, shows up in tab though

### Plugin and Datapack List

Bukkit Plugins:
- FastAsyncWorldEdit, ProfileTest

### Paper version

1.19.4 - 477

**Comment by Owen1212055** [comment]
Have been investigating this, all the packets appear to be correctly sent...

It appears that the update player info packet uses the uuid stored in the player, not the game profile one. So, when the player entity is sent, it tries to use the one set by the game profile, not the one by the entity. This causes essentially the add player packet to be ignored since the UUIDs don't match..

Attempting to modify the uuid to fix this causes players to be kicked with a chat session invalidation error, so, I'm not really sure what's the best way to tackle this. As, it seems that changing the uuid is unsafe.
