### ISSUE TITLE
Villagers "forgetting jobsite blocks"

### ISSUE THREAD

**Issue by DavidMick** [PaperSpigot/Paper#9154]
### Expected behavior

Once a villager obtains a job site block, as long as it can path find to it, it should work fine and no other villager should obtain the same job site block.

### Observed/Actual behavior

Villagers with default spawn reason tend to, for a lack of a better term, forget their job site block as if it was broken and then it allows for other villagers to obtain the same job site block. Villagers that had the job site lock their trades and never refill.

### Steps/models to reproduce

Just give a villager (with default spawn reason) a job site block and after about 20 minutes it occurs.

### Plugin and Datapack List

Plugins:
Spark
No datapacks installed

### Paper version

This server is running Paper version git-Paper-510 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bd35d60)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

**Comment by Phoenix616** [comment]
Does this happen with no other Villager around too? And did the other Villager have the same Profession before? Because Villagers of the same profession will compete for any job site in the radius (see `PoiCompetitorScan`) and the one with the most experience will "win", removing the job site from the looser.

**Comment by lynxplay** [comment]
Closing this as stale.
