### ISSUE TITLE
Player#sendBlockDamage overlaps vanilla block-damage

### ISSUE THREAD

**Issue by Boy0000** [PaperSpigot/Paper#9232]
### Expected behavior

When repeatedly sending a block-damage change to players via Player#sendBlockDamage, it should not have visual artifacts with overlapping the vanilla breaking stage

### Observed/Actual behavior

Here is an example when using the following:
```kt
            do {
                block.location.getNearbyPlayers(16.0).forEach { p ->
                    p.sendBlockDamage(block.location, stage.toFloat() / 10, player.entityId)
                }
                delay(breakTime / 10)
            } while (player.toGeary().has<PlayerIsMining>() && stage++ < 10)
```
https://github.com/PaperMC/Paper/assets/62521371/6dcf522b-fffe-4888-9a40-7167028ce718

Using the following code fixes the issue. Only real change I can see is that the location.hashcode is set to where the Player-method sets entityId
```kt
private fun Player.sendBlockDamage(location: Location, stage: Int) {
        val packet = protocolManager.createPacket(PacketType.Play.Server.BLOCK_BREAK_ANIMATION)
        packet.integers.write(0, location.hashCode()).write(1, stage)
        packet.blockPositionModifier.write(0, BlockPosition(location.toVector()))

        protocolManager.sendServerPacket(player, packet)
    }
```

https://github.com/PaperMC/Paper/assets/62521371/f1633c22-3ceb-4438-be97-4ab1ca24e349

### Steps/models to reproduce

1. Listen to BlockDamageEvent or the packet
2. Cancel it and add own logic for incrementing the damage-stage
3. Get this issue unless setting `entityId` to the location.hashcode()

### Plugin and Datapack List

[17:50:50 INFO]: Server Plugins (24):
[17:50:50 INFO]: Paper Plugins:
[17:50:50 INFO]:  - BKCommonLib, HuskHomes
[17:50:50 INFO]: Bukkit Plugins:
[17:50:50 INFO]:  - Blocky, BondrewdLikesHisEmotes, Bonfire, Breaker, Chatty, DeeperWorld, *FlySpeed, Geary, Guiy, HMCCosmetics
[17:50:50 INFO]:  LightAPI, Looty, LuckPerms, MineInAbyss, MythicMobs, PlaceholderAPI, PlugManX, ProtocolLib, ShulkerPacks, SignLink
[17:50:50 INFO]:  TCCoasters, Train_Carts

### Paper version

[17:51:01 INFO]: Checking version, please wait...
[17:51:01 INFO]: This server is running Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)

### Other

Looking into the NMS-class of the packet it seems the ID-field here is misrepresented in the method.
The sourceId should be the location hash not an entity?

![image](https://github.com/PaperMC/Paper/assets/62521371/b572a565-66f5-452f-b2cf-723f2dd878d8)

Looking at the method is says "entity id of the entity the damage belongs to"
Might be correct in another instance, though not sure when that would ever be the case?
![image](https://github.com/PaperMC/Paper/assets/62521371/9adde22e-1c97-4a5b-95a3-522de2d12ef6)

**Comment by Owen1212055** [comment]
The issue you are experiencing is due to how block damage is keyed. Block damage is keyed by the entity that is doing the destruction, so in this case, the player that is destroying the block. When using the send block damage method, it is overriding the damage progress set by the client, and since you are sending a different damage source, it is causing "desync" of some sort.

When trying to override the client-side block damage, using the player's own entity ID causes this odd behavior. So, that is why when using a location hashcode it works, as it's not modifying the player set damage progress anymore.

Keying it by the location hashcode doesn't make sense, because you could have multiple different entities breaking the same block. But, normally, you cannot have the same entity breaking multiple blocks. 

I'm going to close this for essentially not an issue, as this is in general just a quirk with how it works.
