### ISSUE TITLE
Loading of new chunks is unusually slow

### ISSUE THREAD

**Issue by creeper-0910** [PaperSpigot/Paper#9304]
### Expected behavior

New chunks should take a few seconds or so to load.

### Observed/Actual behavior

If you go to a chunk of the overworld that has never been read in the nethergate, an error is logged in the console and it takes about 2 minutes to load the chunk.

### Steps/models to reproduce

Stacktrace: https://pastebin.com/WbpgU2Kn
1.A nether gate is placed about 1000 blocks away to generate a new chunk of the overworld.

### Plugin and Datapack List

|Plugin||
| --- | --- |
||AllowToConnect v1.0.0|
||CoreProtect v21.3|
||CustomWelcome v1.4|
||HiddenArmor v1.1.0|
||Geyser-Spigot v2.1.1-SNAPSHOT|
||floodgate v2.2.2-SNAPSHOT (b59-2278589)|
||DiscordSRV v1.26.2|
||LunaChat v3.0.16|
||PlaceholderAPI v2.11.3|
||ProtocolLib v5.0.0|
||spark v1.10.41|
||GSit v1.4.5|

### Paper version

This server is running Paper version git-Paper-8 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 3722877)
You are running the latest version
Previous version: git-Paper-4 (MC: 1.20)

### Other

"THIS IS NOT A BUG OR A CRASH", but the problem happened after I updated to 1.20.
I migrated this server from 1.19.4 and had no problems before the migration.

**Comment by Owen1212055** [comment]
Is this still the case as of 1.20.1?

**Comment by creeper-0910** [comment]
Yes.
However, this error stopped occurring after we migrated to a new server.
I don't know why as the configuration has not been changed...

**Comment by allanger** [comment]
> Is this still the case as of 1.20.1?

In my case, it's only happening after the 1.20.1 update

**Comment by Owen1212055** [comment]
In general it's hard for us to go on a basis here. Functionality may have changed as 1.20 redid some of the chunk system.

Feel free to leave a comment with some profiler information and we can perhaps look into this a bit more and reopen it.

Thank you! 😃

**Comment by Alienlex** [comment]
On my test server its been happening since late 1.19.4 and still happens in 1.20.1. The only thing we are sure of is that its being caused by the garbage collector. When the garbage collector collects the first time after server start it causes a 5+ second lag spike. This was tested on both a completely vanilla paper server, and with our test server which has all custom homemade plugins. 

once that initial garbage collector spike happens everything seems fine, until just one player begins flying around at high speeds. Then there is noticeable lag. 

I would like to try and provide whatever helpful information I can, and I can replicate the bug easily. I just don't know where to find the profiler information you need

**Comment by electronicboy** [comment]
We have 0 control over the behavior of GC, the fact that you're saying that after the first GC cycle runs stuff is fine, that would generally suggest that either the issue is waiting for JIT to warm up, which is gonna be slower in modern MC due to the complexity of the chunk system, as well as some level of an environmental issue. We pretty much have 0 control over how the JVM behaves here
