### ISSUE TITLE
Spigot.yml option 'send-namespaced' is not respected for console commands

### ISSUE THREAD

**Issue by WiIIiam278** [PaperSpigot/Paper#9309]
### Expected behavior

The spigot `send-namespaced` option disables namespace-backed commands from being displayed in TAB completion. I expect with this option set to `true`, namespaced commands will not be suggested in TAB completion anywhere.

### Observed/Actual behavior

Namespace-backed commands were correctly not suggested in TAB completions in-game, but still displayed when TAB completing commands through the server console.

### Steps/models to reproduce

Enable `namespaced-commands` in the spigot.yml config file and observe as you can still TAB complete namespace-backed `minecraft:` commands in console (but not in-game)

### Plugin and Datapack List

n/a

### Paper version

* 1.19.4-483368e
* 1.20-3722877
* Also tested with the latest paperclip from the brigadier commands PR

**Comment by Machine-Maker** [comment]
The reason why the option is called `send-namespaced` is because all it does, is disable the namespaced commands from being "send" to the client. It doesn't remove them, and if a client manually typed one out, it would still work. As the console isn't a client, and doesn't need to be sent the commands, I'd say this is works-as-intended.
