### ISSUE TITLE
Server crash when removing entity

### ISSUE THREAD

**Issue by SoSeDiK** [PaperSpigot/Paper#9464]
### Stack trace

Server log: https://paste.gg/p/anonymous/203db4bac18c42b79b95ed3f816fe91d
Crash log: https://paste.gg/p/anonymous/49f1d285f8ea45ef9bfc48b774a074af

### Plugin and Datapack List

\> plugins
[16:39:09 INFO]: Server Plugins (1):
[16:39:09 INFO]: Bukkit Plugins:
[16:39:09 INFO]:  - Testik

\> datapack list
[16:40:13 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[16:40:13 INFO]: There are no more data packs available

### Actions to reproduce (if known)

Removing entity upon EntityRemoveFromWorldEvent caused by chunk unload leads to a crash.

Can be reproduced by using listeners with the following code:
```java
private @Nullable Pig coolPig;

@EventHandler
public void onChat(@NotNull AsyncChatEvent event) {
	Player player = event.getPlayer();
	Bukkit.getScheduler().scheduleSyncDelayedTask(this, () -> {
		coolPig = player.getWorld().spawn(player.getLocation(), Pig.class);
	});
}

@EventHandler
public void onDespawn(@NotNull EntityRemoveFromWorldEvent event) {
	if (!(event.getEntity() instanceof Interaction)) return;
	if (coolPig == null) return;

	if (coolPig.isValid()) coolPig.remove();
	coolPig = null;
}
```
Proceed with the following steps:
- Spawn Interaction entity somewhere (`/summon minecraft:interaction`).
- Spawn a pig (by typing into chat).
- Make chunk with the interaction entity unload (leaving sever/going far) and observe the crash,

---
Edit: after dozens of tries, seems like the crash is not 100% consistent.
Using the following listener instead of a chat one:
```java
@EventHandler
public void onLoad(@NotNull EntitiesLoadEvent event) {
	for (Entity entity : event.getEntities()) {
		if (!(entity instanceof Interaction)) continue;
		coolPig = entity.getWorld().spawn(entity.getLocation(), Pig.class);
		return;
	}
}
```
And joining the server with the chunk in which the interaction entity is placed (make sure it's not a spawn-loaded chunk) leads to the same crash too.

### Paper version

\> version
[16:38:22 INFO]: Checking version, please wait...
[16:38:22 INFO]: This server is running Paper version git-Paper-69 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6b325cd)
You are running the latest version
Previous version: git-Paper-64 (MC: 1.20.1)

### Other

It'd be also nice to have a way of distinguishing when EntityRemoveFromWorldEvent is caused by chunk unload (because in my case I'd prefer to omit many singular entity calls in favor of one EntitiesUnloadEvent).

**Comment by ewof** [comment]
same problem i made issue on folia https://github.com/PaperMC/Folia/issues/126 (i mention in issue i had on paper too)
i thought it was towny but lldm fixed what thought could be causing it and i still get it, after paper build 69/70 it stopped happening but it happens again on latest build

**Comment by electronicboy** [comment]
same exception, different issue

**Comment by lynxplay** [comment]
Well, as a summary, https://github.com/PaperMC/Paper/blob/c016e039a5b7c0e86a2862235451b09a315d12cc/patches/server/0019-Rewrite-chunk-system.patch#L16314-L16328 is the "culprit" here.

We are updating the status of the entities in the entity slice, which triggers the respective entity events. However, this logic acts, from my understanding, on live data (`this.entities.getRawData()` does not create a copy for obvious performance benefits), so when elements are removed from the slice during the for-loop, this explodes as
A) Elements in the slice shift (is this related to potential double ticking causing retiring exceptions on the entity scheduler ? who knos)
B) The count is retrieved once and stored, meaning that the logic will encounter null entities and well, there is our exception.

**Comment by ewof** [comment]
bros can someone fix this ill pay like $200

**Comment by Spottedleaf** [comment]
This crashing behavior really isn't introduced by Paper. Vanilla will be vulnerable to CME if removing an entity in the same chunk section while unloading a chunk, but Paper is vulnerable for the entire chunk. So while the circumstances may be different to produce it, it's still rooted in just how the chunk system works in Vanilla. It would be nice to make it more resistant to this stuff, but that has the _other_ problem of making the unload callbacks for entity possibly broken which was _always_ a constant headache in previous versions.

Generally you should not be modifying world state while listening to the entity remove event, as it is invoked any time an entity is removed - as a result, the possible side effects are quite large. There are a lot of places in Vanilla it will be invoked, and a lot of places in plugins that you don't know about where it will be invoked. This is why it has no reason, you aren't supposed to be using it this way. It was only ever designed so that plugins could clean up plugin state related to entities.

I'm not going to fix the crash, rather I'm going to add a check for this behavior and make it fail when it happens with a reasonable message - just how the rest of the chunk system works with behavior similar to this.

I suggest making your logic delay the removal to the next tick. However, you will need to consider the timing implications of doing that.

**Comment by SoSeDiK** [comment]
I think having a reasonable message and a javadoc notice would be enough.

In my case, I have a map of custom tracked entities and use `EntityRemoveFromWorldEvent` for cleaning up.

One of such custom entities has a linked child Entity inside of it that I call `#remove` on upon the parent's removal from the world, which leads to this crash.

I guess the solution is to delay by one tick and check before removal if the chunk is still loaded and my child entity is still valid?

**Comment by ewof** [comment]
is it possible to make it show which plugin last tried to remove an entity in the crash report?
