### ISSUE TITLE
Don’t deprecate String messages

### ISSUE THREAD

**Issue by DerEchtePilz** [PaperSpigot/Paper#9489]
### Is your feature request related to a problem?

At the moment, it seems like Paper is trying (or rather is already) deprecating all methods that use Strings to fill something with content.
You want to send a message? Use Components.
You want to add a lore to items? Use Components.
My problem with this:
- It creates an incompatibility with any server still running on Spigot requiring you to write a Spigot-dedicated plugin if you try to support as many servers as possible.
- It requires you to create an extra object when in reality this shouldn’t be the case. If I want to send a message to a player it’s sufficient to use a String. If I want to edit the ItemMeta, I don’t need Components, I can achieve everything by using, you guessed it, Strings.

### Describe the solution you'd like.

I don’t necessarily want to remove the Component message methods.
But it is much easier to have the _option_ to be able to choose whether you want to use a Component or a String.

### Describe alternatives you've considered.

Alternatives I considered is switching to Kotlin to write extension functions that effectively let me write Strings but this still creates an incompatibility with any Spigot servers I may also want to support.

**Comment by olijeffers0n** [comment]
You still can use strings? There is no compatibility break however the components are simply more powerful API than just being able to have colours with an enum.

**Comment by lynxplay** [comment]
> It creates an incompatibility with any server still running on Spigot requiring you to write a Spigot-dedicated plugin if you try to support as many servers as possible.

It does not. These methods still work, they are simply deprecated because the format they are using is outdated and does not properly reflect the technical abilities components have in the game. (See gradients, click events, etc). You can still use these methods and just ignore a deprecation warning. It is not a deprecation warning for removal, these methods are not gonna vanish from existence too soon into the future as that would obviously be a major break in backwards compatibility.

> It requires you to create an extra object when in reality this shouldn’t be the case. If I want to send a message to a player it’s sufficient to use a String. If I want to edit the ItemMeta, I don’t need Components, I can achieve everything by using, you guessed it, Strings.

Idk if this is supposed to be an argument for performance ? the legacy text based methods are not magical, they do some heavy parsing logic for you under the hood to in the end, well, end up with a component. The internals have been component based for literal years now, the string methods simply "allow" you to use an incomplete format to define these components. Alternatives like mini message or even minedown (hi phoenix) are much more suited to represent components are strings. The component methods actively allow you to *skip* the deserialiser that would otherwise always have to happen when using legacy text.

**Comment by DerEchtePilz** [comment]
> It does not. These methods still work, they are simply deprecated because the format they are using is outdated and does not properly reflect the technical abilities components have in the game. (See gradients, click events, etc). You can still use these methods and just ignore a deprecation warning. It is not a deprecation warning for removal, these methods are not gonna vanish from existence too soon into the future as that would obviously be a major break in backwards compatibility.

I am not saying they aren't useful. Imo, they are just way to overkill when just trying to _send a simple message_.

> > It requires you to create an extra object when in reality this shouldn’t be the case. If I want to send a message to a player it’s sufficient to use a String. If I want to edit the ItemMeta, I don’t need Components, I can achieve everything by using, you guessed it, Strings.
> 
> Idk if this is supposed to be an argument for performance ? the legacy text based methods are not magical, they do some heavy parsing logic for you under the hood to in the end, well, end up with a component. The internals have been component based for literal years now, the string methods simply "allow" you to use an incomplete format to define these components. Alternatives like mini message or even minedown (hi phoenix) are much more suited to represent components are strings. The component methods actively allow you to _skip_ the deserialiser that would otherwise always have to happen when using legacy text.

I don't care about performance. I am simply saying that you should't discourage anyone from using these methods because you think messages aren't enough to display what you want. As mentioned before, I don't think that `Component`s aren't useful and they might make sense when displaying messages.
However, when talking about the lore of an item I think they are totally useless. You can't click on the lore, you can hover over the lore.
Additionally, the deprecation of `setLore()` for example. Why did that happen?

**Comment by lynxplay** [comment]
Yea I get your point and I partially agree, obviously constructing a full component yourself is a lot more verbose than legacy text. There is 100% an argument to be made that a string based format can have its advantages, just for the speed of typing and line length, however using a format that is not complete simply is not the way forward. Between MiniMessage and other alternatives, string based representations of components are 100% useful.

I can also see a point to be made to somehow represent an option to nicely integrate these formats in the API.
Does not mean that the deprecated methods should be un-deprecated. The legacy format is simply not powerful enough so when picking between a potential future string based format for components available in the API, we'd be stupid to pick legacy text as the only thing that format brings is simple colours and terribly looking rgb colours (§x§f§f§0§0§0§0), so the methods are deprecated as they are discouraged from being used over either you constructing the component directly in code or parsing a component with a completed format (mini message etc) and feeding that into the component methods.

**Comment by DerEchtePilz** [comment]
> so when picking between a potential future string based format for components available in the API, we'd be stupid to pick legacy text

So you don't get my point. You are not supposed to choose between the String methods and the Component methods. You are supposed to _offer_ both ways.
I'd say in at least 70% of all cases, it's enough to just send a message that doesn't need to have any clickable components. A feedback message for a command or simply instructions in the chat don't need fancy components because you are supposed to just read it.
I mean, which option are you choosing to send a simple message to a player?
Option 1:
```java
player.sendMessage("Hey, this is a message. Nice, beautiful and compatible with Spigot.");
```
or
Option 2:
```java
player.sendMessage(Component.text("For some stupid reason, I need to wrap a message in a Component requiring me to write 16 obsolete characters which also require one more import and causes the message to not be able to be sent on a Spigot server."));
```

I mean, out of these options, for me personally, option 1 would be the obvious choice. I'd be ensuring that my plugin works on Spigot and Paper and I avoid some useless wrapping.

**Comment by kennytv** [comment]
If you want to send messages without formatting, use sendPlainMessage. If you want to send messages with formatting in a  string format, use sendRichMessage

**Comment by electronicboy** [comment]
Mojang deprecated legacy text for removal 8 years ago, the rest of the community moved on towards component based systems, spigots refusal to support modern conversions doesn't mean that we're going to shoot ourselves in the foot and not move forward with the rest of the community.

We are offering both ways, you can still use legacy text using the legacy serialisers, rather than the server handling the extra layer of conversions it needs to go through, you can use adventure, which supports a more standardised legacy format in the wider community rather than whatever md decides to implement.

both options will still work for some period of time, but we're not going to commit to maintaining craftbukkits broken legacy conversion logic for another 10 years, it's already wasted enough of our time.

**Comment by DerEchtePilz** [comment]
I've got one last question after I spent a few days thinking about all this:
Why not make it possible (or undeprecated) to use sendMessage(String) but in the CraftBukkit implementation, this is redirected to sendMessage(Component) using Component.text(Message)?
I mean I get the advantage of proper styling with components but I still feel like an API should provide a (few) helper method(s) to accomplish the same thing with multiple ways.
Anyway, I'll be thankful for an answer and will not further bother you with this (although I could see its usefulness).

**Comment by electronicboy** [comment]
Because you shouldn't be putting legacy text inside of components, adventure even warns for that by default outside of that. if you want to send a plain message, use the method to send a plain message, otherwise, use the serializers.

There's little interest for us to go out of our way to maintain this broken, lossy format; especially when more powerful and flexible alternatives exist which are used by the entire community. Having 20 different ways to do 1 thing just incurs extra debt on our part rather than just trying to move forward with the rest of the community.
