### ISSUE TITLE
Stonecutter recipes are displayed incorrectly

### ISSUE THREAD

**Issue by Wupin** [PaperSpigot/Paper#9499]
### Expected behavior

Recipes in stonecutter should show the result of the recipe

### Observed/Actual behavior

Recipes in stonecutter are incorrectly displayed , examples in pictures
![image](https://github.com/PaperMC/Paper/assets/22504664/612535e8-db8f-432c-96a1-263ea3f20531)
![image](https://github.com/PaperMC/Paper/assets/22504664/98732a9e-a5c2-499e-a44d-ae226610c5a3)

### Steps/models to reproduce

Register more than 2 recipes, the method im using to register recipes:
```
for (int i = 1; i < 10; i++) {
  NamespacedKey key = new NamespacedKey(this, "crsc_" + i);  
  StonecuttingRecipe recipe = new StonecuttingRecipe(key, makeItem(i), Material.OAK_PLANKS);  
  Bukkit.addRecipe(recipe);  
}
```

### Plugin and Datapack List

> plugins
[02:29:45 INFO]: Server Plugins (1):
[02:29:45 INFO]: Bukkit Plugins:
[02:29:45 INFO]:  - wShop
> datapack list
[02:29:48 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[02:29:48 INFO]: There are no more data packs available

### Paper version

This server is running Paper version git-Paper-82 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b533905)
You are running the latest version
Previous version: git-Paper-22 (MC: 1.20.1)

**Comment by Machine-Maker** [comment]
As far as I know, this is 100% unfixable by Paper. This is an issue with how recipes are handled between the server and the client, and would require a client fix as well. It isn't even a "vanilla issue" because there is no way to add recipes that would cause such an issue in vanilla. 

----

The issue stems from how the clicked button is communicated to the server to select which recipe. Let's start at the beginning:
1. When a client joins the server, the complete list of recipes is sent to the client in some order.
2. That list of recipes is then added to the `RecipeManager` on the client. The client uses collections that do not preserve order to store these recipes, so already we know that recipes are not ordered the same way on the client as the server. This is never an issue however, as nothing relies on the order of recipes
3. The Stonecutter DOES rely on the order of recipes to know what index to send to the server to know what recipe was selected. The client solves this by *sorting* the recipe list when it is requested by the stonecutter screen. But this sorting algorithm is only based on the *translation key* for the result itemstack. This means that any custom nbt is not included in the sorting algorithm.
4. This causes recipes which have identical output itemstack translation keys to have an undefined order which may differ from the order of the recipes the `StonecutterMenu` requests to know what index maps to what recipe.

**Comment by Machine-Maker** [comment]
As of 24w10a, this is now probably a vanilla issue and I have opened a [bug report](https://bugs.mojang.com/browse/MC-269161) accordingly.
