### ISSUE TITLE
Nether portal not working

### ISSUE THREAD

**Issue by usma0118** [PaperSpigot/Paper#9539]
### Expected behavior

Player is able to transport via Nether portal.

### Observed/Actual behavior

Nether Portal are not transporting player to Nether.
I have tried creating a new one. Same issue.
Had also tried by removing all plugins.

If I try to teleport to Nether (even in creative mode). Player dies immediately 

### Steps/models to reproduce

None

### Plugin and Datapack List

file/bukkit
TCPShield

### Paper version

This server is running Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a40e48f)
You are running the latest version
Previous version: git-Paper-97 (MC: 1.20.1)

**Comment by saturnux** [comment]
Just a question :
did you activate:
nether-ceiling-vacuum-damage-height
in paper-world-default or paper-woerld-nether

because :
with multiverse I had this problem. disabling it solves transport over nether

**Comment by usma0118** [comment]
It's set to 
nether-ceiling-void-damage-height: 0

**Comment by usma0118** [comment]
> It's set to nether-ceiling-void-damage-height: 0

Interesting… After looking at thread: #1939 

I have changed the value from 0 to disabled and nether behavior is working as expected.

**Comment by Machine-Maker** [comment]
> It's set to
nether-ceiling-void-damage-height: 0

This means that if the player is above 0 y-coord in the nether, they will take void damage. There is logic that prevents portals from spawning above that coordinate if it is set, so that is why portals weren't spawning in. The default is `disabled`, and any paper config files that existed before the `disabled` value was added were automatically migrated, so perhaps you copied it from an older un-migrated configuration.

Anyways, this is works as intended and it sounds like you solved your issue then by disabling that setting.
