### ISSUE TITLE
Limit the number of pages of the book

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#9659]
### Is your feature request related to a problem?

Now the restrictions on the book are quite comprehensive, but I feel that there are still some shortcomings
Most people have a vague idea of word count

### Describe the solution you'd like.

The book can save 100 pages by default, can you add an option to customize the maximum number of pages of the book, such as the maximum number of pages of 20 pages
It seems nice to give tips on restrictions
Instead of kicking out the player directly

### Describe alternatives you've considered.

null

### Other

null

**Comment by Malfrador** [comment]
The existing options (in the global configuration, `book-size`) already allow you to ensure that a book doesn't get too large for the server to handle, though the default values aren't perfect.
They are configured in bytes and not pages, because pages can have very different sizes depending on the characters used on them. 
Because of this, a page limit isn't really the best way to protect against book-related exploits.

If you want to limit the page count for some other reason, a plugin can do that using the API.

**Comment by welove69** [comment]
> The existing options (in the global configuration, ) already allow you to ensure that a book doesn't get too large for the server to handle, though the default values aren't perfect. They are configured in bytes and not pages, because pages can have very different sizes depending on the characters used on them. Because of this, a page limit isn't really the best way to protect against book-related exploits.`book-size`
> 
> If you want to limit the page count for some other reason, a plugin can do that using the API.

Well, it's just that players sometimes don't know the number of bytes and then get kicked off the server, so I guess it would be more intuitive to limit the number of pages, I'm seeing if there is a similar plugin

**Comment by electronicboy** [comment]
except it wouldn't be intutive, as theres no way to convey the limit to end users; all we can do is respond after the fact, it's not like we can display to them in some form or useful manner that they're exceeding the limit and what they're writing is going to be trashed, etc
