### ISSUE TITLE
Villager trading don't work on 1.20.2 

### ISSUE THREAD

**Issue by RunqRun** [PaperSpigot/Paper#9764]
### Expected behavior

Basiclly, when I click the villager, left side is shown some rows.

### Observed/Actual behavior

![image](https://github.com/PaperMC/Paper/assets/91005690/79cac3ae-7578-49f7-8454-915cb8817d12)
like this image, left side is shown nothing.
so we cannot trade something with villager.

### Steps/models to reproduce

just spawn the villager, and place a job site block
and then, click them.

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/91005690/d587e153-8575-4b60-8b39-35d2d7a000f8)
![image](https://github.com/PaperMC/Paper/assets/91005690/aae37534-44c0-4efa-a404-bfa0f6a189ec)

### Paper version

![image](https://github.com/PaperMC/Paper/assets/91005690/08154a0c-3a15-40b4-9be8-7432cd7b2df8)

**Comment by Leguan16** [comment]
Is that Bedrock Edition?

**Comment by MiniDigger** [comment]
please try without plugins using a vanilla client.

**Comment by elyrodso** [comment]
I remember that one of the three ViaPlugins caused a problem with villagers when using a new version.

Specifically in my case, it was when 1.19 was released, but the server was still on 1.18 and ViaVersion was used to allow players from 1.19, and all trades were not available, so probably this is not caused by Paper, but rather an existing problem caused by one of these plugins.

**Comment by CodeByCam** [comment]
I haven't been able to reproduce this on the latest Paper 1.20.2 build with no plugins. Considering you're running ViaVersion/Backwards/Rewind, it's safe to assume this is an issue with one of those plugins. You can try to seek support on their [Discord](https://discord.com/invite/viaversion), or through their [GitHub](https://github.com/ViaVersion/).
