### ISSUE TITLE
Update ASM on (key) legacy versions

### ISSUE THREAD

**Issue by PukPukov** [PaperSpigot/Paper#9790]
### Is your feature request related to a problem?

Old ASM can't transform classfiles compiled on new Java. ASM used by spigot in the process of loading plugins. This efficiently prohibits usage of new java versions to every plugin developer, because no one want to write plugins that supported only on last version (only 50,5% of servers supports latest java (running 1.20.1+ now) and this number will not change in the future). 

### Describe the solution you'd like.

Update ASM to latest version on legacy branches, like was done in 2021 with log4j due to log4jshell

**Why this case is unique and unrelated to ideas of backporting every other patch to every older version?**
Because task of creating plugin, that supports multiple minecraft version, is much more difficult if there is java version conflict. If it is possible to run every version on latest java, we can write some unification api and use it (something like paperlib, except for the paperlib is supposed to unify paper and spigot, and not for example 1.12.2 and 1.20.2). If we have to unify multiple versions with the java version conflict, we have to write alternative java compiler to allow compilation of new java syntax to old classfile standard, that supports by old JVM. There was such projects, but, as far as i know, they all are dead. 

### Describe alternatives you've considered.

Create version independent plugin-loader (something like fabric did) with immutable API, change all legacy versions to use it, and in future, if ASM (or something else) will again require update to support plugins on new java, just update plugin-loader and don't change main server code in all legacy branches. The server owners will should just update plugin-loader.jar to run new plugins. Harder, but cleaner, and more interesting to implement.

**Comment by lynxplay** [comment]
At least my two cents on this.
We want the number of people running latest paper to change. Having large quantities of people run outdated versions means people have to jump through hoops to support these dead versions.

Log4J was updated because it allowed remote code execution and posed a real security risk. Given we still offered downloads to those old versions, we patched it as offering software with know vulnerabilities like this is just bad practice.

If people are planning on running old Minecraft versions in production, they should do so on a maintained fork for that version, not on a years old paper build that has not been touched (outside of the Log4J patch) in forever.

The fact that Log4J was updated does not remotely mean these versions are maintained. They actively aren't. I don't think it is in our interest to set a precedent of updating these versions whatsoever (outside of a vulnerability as bad as Log4J). If you want to support them, it is up to you to suffer the consequences of java 8.

**Comment by Leguan16** [comment]
Except you could just use older versions of Java or not?

**Comment by ancap-kun** [comment]
> even if we would release updates, nobody would update their servers.

I think people don't update to new versions not because they are too lazy to drop new paper.jar. They think that new versions are less performant (it's true in some cases), and also to update to new version of game they should not just update server.jar, but a lot of plugins, that, for example, use NMS or works with packets. In this case of new build inside one game version you can just tell in plugin readme page to use latest build and everyone will do this.

**Comment by MiniDigger** [comment]
no, I was saying even if we release a new build for a legacy version, which we are not going to do, nobody would download it. you could spend ages chasing your users to update to that new build.
many servers down even update when a version is still supported, they just download whatever is latest when they update to a new mc version and call it a day. 

this wouldn't have the effect you want it to have and it would set a bad precedent of us supporting old versions for writing plugins for old versions, which we dont support.

we will not stop you from supporting old versions and we will try to not make is unnessasarily hard to do it, but we will not help you. 

if you choose to support old versions, you also choose the pain that comes with it, not being able to use new api or new java versions is part of that.

the goal is to move everybody to latest. if you support old versions you enable server owners to not update, thus you are part of the problem.

**Comment by ancap-kun** [comment]
>we will not stop you from supporting old versions and we will try to not make is unnessasarily hard to do it, but we will not help you.

May i do pull request with it myself?

**Comment by lynxplay** [comment]
We don't stop you from writing plugins that support old versions. A pr to old versions will not be accepted.

**Comment by Leguan16** [comment]
No one is stopping you. 

But i can tell you that it will be closed within 10 seconds.
