### ISSUE TITLE
Unable to join server and server crash

### ISSUE THREAD

**Issue by PhantomDevIndie** [PaperSpigot/Paper#9894]
### Expected behavior

I expected just connect to my server like a player.

### Observed/Actual behavior

When I tried to start my server crashed

### Steps/models to reproduce

I tried to use the Iris plugin but I had to downgrade server version, and so I did, but when it fired up it just crashed!
Then i created another server same plugins an all those things and that server just disconnects player on join.

### Plugin and Datapack List

BountyPlus-1.0-SNAPSHOT.jar
Citizens.jar
CustomScoreboard.jar
DailyRewards.jar
EssentialsX-2.21.0-dev+16-b900444.jar
EssentialsXChat-2.18.0.0.jar
ExcellentCrates-5.0.0.jar
floodgate-spigot.jar
Geyser-Spigot.jar
HolographicDisplays.jar
Iris-2.8.1-1.20.1.jar
Lockette.jar
LuckPerms-Bukkit-5.4.102.jar
multiverse-core-4.3.12.jar
MyCommand.jar
NametagEdit
NametagEdit.jar
NexEngine.jar
PlaceholderAPI-2.11.3.jar
ProtocolLib.jar
RealisticSeasons-10.6.0.jar
SkinsRestorer.jar
SMPtweaks-1.0.23.jar
TAB v4.0.7.jar
TerraformGenerator-11.1.1_1.16.5-1.20.2.jar
TradeSystem_v2.5.2.jar
TrollBoss_v6.5.3.jar
UltimateShop-1.5.2.jar
Vault.jar
ViaBackwards-4.8.1.jar
ViaRewind-3.0.3-SNAPSHOT.jar
ViaVersion-4.8.1.jar
VoidGenerator.jar
worldedit-bukkit-7.2.17.jar

### Paper version

I am using Paper 307 for minecraft 1.19.2.

### Other

https://github.com/PaperMC/Paper/assets/108987120/47e8df89-a60a-4dda-bdc1-df629cada025

**Comment by lynxplay** [comment]
1.19.2 is no longer supported.
Additionally, if you can replicate this on latest paper, please provide the entire server log instead of a small video of what looks to be a console.

I'll be closing this issue as unsupported till then.
You can also simply ask in our [discord](https://discord.gg/papermc) as I doubt this is really a paper issue more an issue in figuring out what kills your server, which github is not a nice place to investiage.
