### ISSUE TITLE
Patch the copper bulb to a 1-tick delay

### ISSUE THREAD

**Issue by TheBlckbird** [PaperSpigot/Paper#9983]
### Is your feature request related to a problem?

When Mojang first added the copper bublb, it had a 1-tick delay. This was a pretty big deal for Redstone, because Redstone usually runs at even game ticks so this would allow for events to occur at odd game ticks.

### Describe the solution you'd like.

Patch the copper bulb so it has a 1-tick delay. AFAIK this is only server side, so it should be patchable by Paper. Please correct me if I’m wrong.

### Describe alternatives you've considered.

Mojang won’t listen

### Other

It would be awesome if all big Modding- and PluginAPIs were to implement this.

**Comment by lynxplay** [comment]
I don't think this falls into the scope of paper, not even with a config option.

**Comment by electronicboy** [comment]
1) I get the want for this, so I'm not 100% against it, but, configurably diverging from vanilla behavior gets to be a bit weird
2) Most server modding environments generally take the same general stance of: not our motif.

**Comment by TheBlckbird** [comment]
But what about a configuration option? Would that cause any problems if it’s off by default?

**Comment by lynxplay** [comment]
The question is less, can a config option be implemented that's does this (it certainly could, off by default etc) it's more a, does paper want to offer config options that change vanilla behaviour just for the sake of changing it.

Existing config options are either bug fixes, performance improvements or sanitisers for data.
This would not have any motivation beyond "I don't like mojangs decision", which (while maybe reasonable) is not something we have done yet.

Imo it is also not something I'd like to see in paper, mostly because of the somewhat slippery slope that puts paper on for future suggestions of the sort.

**Comment by TheBlckbird** [comment]
Hm, understandable, but I’m pretty sure that there aren’t many people who wouldn’t like this change.

**Comment by Owen1212055** [comment]
Closing, see above reasons. We do not really divert vanilla behavior for things like this.
